-- Generated by scripts/generate-file-shadow-adjudications.mjs. Review both files.
-- V17 adds occurrence-scoped operator adjudications; V15/V16 remain frozen.
-- No record is a byte root, a recovered upload receipt, or a provider operation.
CREATE TABLE file_shadow_adjudications (
  id TEXT NOT NULL PRIMARY KEY CHECK ((typeof(id)='text' AND length(id) BETWEEN 1 AND 36 AND instr(id,char(0))=0) AND length(id)=36 AND id GLOB '????????-????-4???-[89ab]???-????????????' AND replace(id,'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(id,'-',''))=32),
  occurrence_id TEXT NOT NULL REFERENCES file_shadow_occurrences(id) ON DELETE RESTRICT,
  supersedes_id TEXT UNIQUE REFERENCES file_shadow_adjudications(id) ON DELETE RESTRICT,
  request_json TEXT NOT NULL CHECK (typeof(request_json)='text' AND length(CAST(request_json AS BLOB)) BETWEEN 1 AND 81920 AND json_valid(request_json) AND json_type(request_json)='object'),
  request_sha256 TEXT NOT NULL CHECK (typeof(request_sha256)='text' AND length(request_sha256)=64 AND request_sha256 NOT GLOB '*[^0-9a-f]*' AND instr(request_sha256,char(0))=0),
  source_json TEXT NOT NULL CHECK (typeof(source_json)='text' AND length(CAST(source_json AS BLOB)) BETWEEN 1 AND 524288 AND json_valid(source_json) AND json_type(source_json)='object'),
  baseline_json TEXT NOT NULL CHECK (typeof(baseline_json)='text' AND length(CAST(baseline_json AS BLOB)) BETWEEN 1 AND 524288 AND json_valid(baseline_json) AND json_type(baseline_json)='object'),
  source_expected_byte_size INTEGER NOT NULL CHECK(typeof(source_expected_byte_size)='integer' AND source_expected_byte_size BETWEEN 0 AND 104857600),
  source_expected_sha256 TEXT NOT NULL CHECK (typeof(source_expected_sha256)='text' AND length(source_expected_sha256)=64 AND source_expected_sha256 NOT GLOB '*[^0-9a-f]*' AND instr(source_expected_sha256,char(0))=0),
  created_by TEXT NOT NULL CHECK (typeof(created_by)='text' AND length(created_by) BETWEEN 1 AND 256 AND instr(created_by,char(0))=0),
  created_at TEXT NOT NULL CHECK ((typeof(created_at)='text' AND length(created_at) BETWEEN 1 AND 200 AND instr(created_at,char(0))=0) AND julianday(created_at) IS NOT NULL)
) WITHOUT ROWID;
CREATE UNIQUE INDEX file_shadow_adjudications_one_root ON file_shadow_adjudications(occurrence_id) WHERE supersedes_id IS NULL;
CREATE TABLE file_shadow_adjudication_withdrawals (
  request_id TEXT NOT NULL PRIMARY KEY CHECK ((typeof(request_id)='text' AND length(request_id) BETWEEN 1 AND 36 AND instr(request_id,char(0))=0) AND length(request_id)=36 AND request_id GLOB '????????-????-4???-[89ab]???-????????????' AND replace(request_id,'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(request_id,'-',''))=32),
  request_json TEXT NOT NULL CHECK (typeof(request_json)='text' AND length(CAST(request_json AS BLOB)) BETWEEN 1 AND 81920 AND json_valid(request_json) AND json_type(request_json)='object'),
  request_sha256 TEXT NOT NULL CHECK (typeof(request_sha256)='text' AND length(request_sha256)=64 AND request_sha256 NOT GLOB '*[^0-9a-f]*' AND instr(request_sha256,char(0))=0),
  created_by TEXT NOT NULL CHECK (typeof(created_by)='text' AND length(created_by) BETWEEN 1 AND 256 AND instr(created_by,char(0))=0),
  created_at TEXT NOT NULL CHECK ((typeof(created_at)='text' AND length(created_at) BETWEEN 1 AND 200 AND instr(created_at,char(0))=0) AND julianday(created_at) IS NOT NULL)
) WITHOUT ROWID;
CREATE TABLE file_shadow_adjudication_revocations (
  id TEXT NOT NULL PRIMARY KEY CHECK ((typeof(id)='text' AND length(id) BETWEEN 1 AND 36 AND instr(id,char(0))=0) AND length(id)=36 AND id GLOB '????????-????-4???-[89ab]???-????????????' AND replace(id,'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(id,'-',''))=32),
  adjudication_id TEXT NOT NULL UNIQUE REFERENCES file_shadow_adjudications(id) ON DELETE RESTRICT,
  request_json TEXT NOT NULL CHECK (typeof(request_json)='text' AND length(CAST(request_json AS BLOB)) BETWEEN 1 AND 24576 AND json_valid(request_json) AND json_type(request_json)='object'),
  request_sha256 TEXT NOT NULL CHECK (typeof(request_sha256)='text' AND length(request_sha256)=64 AND request_sha256 NOT GLOB '*[^0-9a-f]*' AND instr(request_sha256,char(0))=0),
  created_by TEXT NOT NULL CHECK (typeof(created_by)='text' AND length(created_by) BETWEEN 1 AND 256 AND instr(created_by,char(0))=0),
  created_at TEXT NOT NULL CHECK ((typeof(created_at)='text' AND length(created_at) BETWEEN 1 AND 200 AND instr(created_at,char(0))=0) AND julianday(created_at) IS NOT NULL)
) WITHOUT ROWID;
CREATE TABLE file_shadow_operation_adjudications (
  operation_id TEXT NOT NULL PRIMARY KEY REFERENCES file_shadow_operations(id) ON DELETE RESTRICT,
  adjudication_id TEXT NOT NULL REFERENCES file_shadow_adjudications(id) ON DELETE RESTRICT,
  adjudication_request_sha256 TEXT NOT NULL CHECK (typeof(adjudication_request_sha256)='text' AND length(adjudication_request_sha256)=64 AND adjudication_request_sha256 NOT GLOB '*[^0-9a-f]*' AND instr(adjudication_request_sha256,char(0))=0)
) WITHOUT ROWID;
CREATE VIEW file_shadow_active_adjudications AS SELECT a.* FROM file_shadow_adjudications a
  WHERE NOT EXISTS(SELECT 1 FROM file_shadow_adjudication_revocations r WHERE r.adjudication_id=a.id);

CREATE TRIGGER file_shadow_adjudications_replace_guard BEFORE INSERT ON file_shadow_adjudications BEGIN
  SELECT RAISE(ABORT,'Historical adjudication history is immutable') WHERE EXISTS(SELECT 1 FROM file_shadow_adjudications WHERE id=NEW.id);
END;
CREATE TRIGGER file_shadow_adjudications_update_guard BEFORE UPDATE ON file_shadow_adjudications BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_adjudications_delete_guard BEFORE DELETE ON file_shadow_adjudications BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_adjudication_withdrawals_replace_guard BEFORE INSERT ON file_shadow_adjudication_withdrawals BEGIN
  SELECT RAISE(ABORT,'Historical adjudication history is immutable') WHERE EXISTS(SELECT 1 FROM file_shadow_adjudication_withdrawals WHERE request_id=NEW.request_id);
END;
CREATE TRIGGER file_shadow_adjudication_withdrawals_update_guard BEFORE UPDATE ON file_shadow_adjudication_withdrawals BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_adjudication_withdrawals_delete_guard BEFORE DELETE ON file_shadow_adjudication_withdrawals BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_adjudication_revocations_replace_guard BEFORE INSERT ON file_shadow_adjudication_revocations BEGIN
  SELECT RAISE(ABORT,'Historical adjudication history is immutable') WHERE EXISTS(SELECT 1 FROM file_shadow_adjudication_revocations WHERE id=NEW.id OR adjudication_id=NEW.adjudication_id);
END;
CREATE TRIGGER file_shadow_adjudication_revocations_update_guard BEFORE UPDATE ON file_shadow_adjudication_revocations BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_adjudication_revocations_delete_guard BEFORE DELETE ON file_shadow_adjudication_revocations BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_operation_adjudications_replace_guard BEFORE INSERT ON file_shadow_operation_adjudications BEGIN
  SELECT RAISE(ABORT,'Historical adjudication history is immutable') WHERE EXISTS(SELECT 1 FROM file_shadow_operation_adjudications WHERE operation_id=NEW.operation_id);
END;
CREATE TRIGGER file_shadow_operation_adjudications_update_guard BEFORE UPDATE ON file_shadow_operation_adjudications BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;
CREATE TRIGGER file_shadow_operation_adjudications_delete_guard BEFORE DELETE ON file_shadow_operation_adjudications BEGIN SELECT RAISE(ABORT,'Historical adjudication history is immutable'); END;

CREATE TRIGGER file_shadow_adjudications_insert_guard BEFORE INSERT ON file_shadow_adjudications BEGIN
  SELECT RAISE(ABORT,'Invalid historical adjudication request') WHERE (((SELECT count(*) FROM json_each(NEW.request_json))=15 AND (SELECT count(*) FROM json_each(NEW.request_json) WHERE key IN('requestId','key','occurrenceId','generation','sourceSha256','sourceLocator','expectedBaselineSha256','expectedEpoch','expectedIncarnation','sourceProfile','purpose','purposeStatement','namespaceStatement','evidenceReference','supersedesId'))=15)
    AND ((typeof(json_extract(NEW.request_json,'$.requestId'))='text' AND length(json_extract(NEW.request_json,'$.requestId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.requestId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.requestId'))=36 AND json_extract(NEW.request_json,'$.requestId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.requestId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.requestId'),'-',''))=32) AND json_extract(NEW.request_json,'$.requestId') IS NEW.id
    AND (json_type(NEW.request_json,'$.key')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.key'))=4 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.key') WHERE key IN('consumerKind','consumerId','consumerSubId','fileSlot'))=4)
    AND json_extract(NEW.request_json,'$.key.consumerKind') IS 'project_content_attachment' AND json_extract(NEW.request_json,'$.key.fileSlot') IS 'primary' AND json_type(NEW.request_json,'$.key.consumerId') IS 'text' AND json_type(NEW.request_json,'$.key.consumerSubId') IS 'text' AND length(CAST(json_extract(NEW.request_json,'$.key') AS BLOB))<=65536
    AND (typeof(json_extract(NEW.request_json,'$.occurrenceId'))='text' AND length(json_extract(NEW.request_json,'$.occurrenceId')) BETWEEN 1 AND 256 AND instr(json_extract(NEW.request_json,'$.occurrenceId'),char(0))=0)
    AND json_type(NEW.request_json,'$.generation') IS 'integer' AND json_extract(NEW.request_json,'$.generation') BETWEEN 1 AND 9007199254740991
    AND (typeof(json_extract(NEW.request_json,'$.sourceSha256'))='text' AND length(json_extract(NEW.request_json,'$.sourceSha256'))=64 AND json_extract(NEW.request_json,'$.sourceSha256') NOT GLOB '*[^0-9a-f]*' AND instr(json_extract(NEW.request_json,'$.sourceSha256'),char(0))=0)
    AND (json_type(NEW.request_json,'$.sourceLocator')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceLocator'))=3 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceLocator') WHERE key IN('storeKind','provider','objectKey'))=3)
    AND json_extract(NEW.request_json,'$.sourceLocator.storeKind') IS 'r2' AND json_extract(NEW.request_json,'$.sourceLocator.provider') IS 'r2' AND (typeof(json_extract(NEW.request_json,'$.sourceLocator.objectKey'))='text' AND length(json_extract(NEW.request_json,'$.sourceLocator.objectKey')) BETWEEN 1 AND 4096 AND instr(json_extract(NEW.request_json,'$.sourceLocator.objectKey'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.sourceLocator.objectKey')))>0 AND length(CAST(json_extract(NEW.request_json,'$.sourceLocator.objectKey') AS BLOB))<=4096
    AND (typeof(json_extract(NEW.request_json,'$.expectedBaselineSha256'))='text' AND length(json_extract(NEW.request_json,'$.expectedBaselineSha256'))=64 AND json_extract(NEW.request_json,'$.expectedBaselineSha256') NOT GLOB '*[^0-9a-f]*' AND instr(json_extract(NEW.request_json,'$.expectedBaselineSha256'),char(0))=0)
    AND json_type(NEW.request_json,'$.expectedEpoch') IS 'integer' AND json_extract(NEW.request_json,'$.expectedEpoch') BETWEEN 0 AND 9007199254740991
    AND (json_type(NEW.request_json,'$.expectedIncarnation') IS 'null' OR ((typeof(json_extract(NEW.request_json,'$.expectedIncarnation'))='text' AND length(json_extract(NEW.request_json,'$.expectedIncarnation')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.expectedIncarnation'),char(0))=0) AND length(json_extract(NEW.request_json,'$.expectedIncarnation'))=36 AND json_extract(NEW.request_json,'$.expectedIncarnation') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.expectedIncarnation'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.expectedIncarnation'),'-',''))=32))
    AND (json_type(NEW.request_json,'$.sourceProfile')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceProfile'))=2 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceProfile') WHERE key IN('profileId','configurationRevision'))=2)
    AND (typeof(json_extract(NEW.request_json,'$.sourceProfile.profileId'))='text' AND length(json_extract(NEW.request_json,'$.sourceProfile.profileId')) BETWEEN 1 AND 256 AND instr(json_extract(NEW.request_json,'$.sourceProfile.profileId'),char(0))=0) AND json_type(NEW.request_json,'$.sourceProfile.configurationRevision') IS 'integer' AND json_extract(NEW.request_json,'$.sourceProfile.configurationRevision') IS 1
    AND json_extract(NEW.request_json,'$.purpose') IS 'research_source'
    AND ((typeof(json_extract(NEW.request_json,'$.purposeStatement'))='text' AND length(json_extract(NEW.request_json,'$.purposeStatement')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.purposeStatement'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.purposeStatement')))>0 AND length(CAST(json_extract(NEW.request_json,'$.purposeStatement') AS BLOB))<=16000)
    AND ((typeof(json_extract(NEW.request_json,'$.namespaceStatement'))='text' AND length(json_extract(NEW.request_json,'$.namespaceStatement')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.namespaceStatement'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.namespaceStatement')))>0 AND length(CAST(json_extract(NEW.request_json,'$.namespaceStatement') AS BLOB))<=16000)
    AND ((typeof(json_extract(NEW.request_json,'$.evidenceReference'))='text' AND length(json_extract(NEW.request_json,'$.evidenceReference')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.evidenceReference'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.evidenceReference')))>0 AND length(CAST(json_extract(NEW.request_json,'$.evidenceReference') AS BLOB))<=16000)
    AND (json_type(NEW.request_json,'$.supersedesId') IS 'null' OR (((typeof(json_extract(NEW.request_json,'$.supersedesId'))='text' AND length(json_extract(NEW.request_json,'$.supersedesId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.supersedesId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.supersedesId'))=36 AND json_extract(NEW.request_json,'$.supersedesId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.supersedesId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.supersedesId'),'-',''))=32) AND json_extract(NEW.request_json,'$.supersedesId') IS NOT json_extract(NEW.request_json,'$.requestId')))) IS NOT 1;
  SELECT RAISE(ABORT,'Adjudication request was withdrawn') WHERE EXISTS(SELECT 1 FROM file_shadow_adjudication_withdrawals WHERE request_id=NEW.id);
  SELECT RAISE(ABORT,'Adjudication requires the exact paused primary baseline') WHERE NOT EXISTS(SELECT 1 FROM file_authority_control c JOIN file_shadow_runtime_guard r ON r.singleton=c.singleton WHERE c.singleton=1 AND c.mode='overlap' AND r.enabled=0)
    OR json_extract(NEW.request_json,'$.expectedEpoch') IS NOT (SELECT epoch FROM file_shadow_control WHERE singleton=1)
    OR json_extract(NEW.request_json,'$.expectedIncarnation') IS NOT (SELECT incarnation FROM file_shadow_runtime_guard WHERE singleton=1)
    OR NEW.occurrence_id IS NOT json_extract(NEW.request_json,'$.occurrenceId') OR NEW.supersedes_id IS NOT json_extract(NEW.request_json,'$.supersedesId')
    OR NOT EXISTS(SELECT 1 FROM file_shadow_heads h JOIN file_shadow_occurrences o ON o.id=h.occurrence_id
      JOIN project_content_attachments x ON x.rowid=h.source_rowid AND x.project_content_id=h.consumer_id
      JOIN project_contents c ON c.id=x.project_content_id JOIN projects p ON p.id=c.project_id
      JOIN assets a ON a.id=x.asset_id
      WHERE h.occurrence_id=NEW.occurrence_id AND h.present=1 AND h.source_json=NEW.source_json
      AND h.consumer_kind=json_extract(NEW.request_json,'$.key.consumerKind') AND h.consumer_id=json_extract(NEW.request_json,'$.key.consumerId')
      AND h.consumer_sub_id=json_extract(NEW.request_json,'$.key.consumerSubId') AND h.file_slot=json_extract(NEW.request_json,'$.key.fileSlot')
      AND h.generation=json_extract(NEW.request_json,'$.generation') AND o.source_json=NEW.source_json
      AND o.legacy_store_kind='r2' AND o.legacy_provider='r2' AND o.legacy_object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey')
      AND x.storage_object_id IS NULL AND x.file_id IS NULL AND a.status='ready' AND a.import_id IS NULL
      AND a.r2_key=o.legacy_object_key AND a.sha256=NEW.source_expected_sha256 AND a.byte_size=NEW.source_expected_byte_size
      AND (x.byte_size IS NULL OR x.byte_size=a.byte_size)
      AND (SELECT count(*) FROM assets ar WHERE ar.r2_key=a.r2_key)=1)
    OR NOT EXISTS(SELECT 1 FROM storage_profiles p JOIN storage_profile_runtime r ON r.storage_profile_id=p.id
      WHERE p.id=json_extract(NEW.request_json,'$.sourceProfile.profileId') AND p.configuration_revision=json_extract(NEW.request_json,'$.sourceProfile.configurationRevision')
      AND p.adapter_type='r2' AND r.state IN('read_only','read_write'))
    OR EXISTS(SELECT 1 FROM file_shadow_decisions d WHERE d.occurrence_id=NEW.occurrence_id)
    OR EXISTS(SELECT 1 FROM file_shadow_operations o WHERE o.occurrence_id=NEW.occurrence_id AND (o.status<>'cancelled'
    OR EXISTS(SELECT 1 FROM file_shadow_attempts a WHERE a.operation_id=o.id AND (a.write_started_at IS NOT NULL OR a.verified_at IS NOT NULL OR a.state NOT IN('failed','cancelled')))
    OR EXISTS(SELECT 1 FROM file_shadow_decisions d WHERE d.operation_id=o.id)));
  -- Never override existing receipts, mappings, derivation, or lifecycle evidence.
  SELECT RAISE(ABORT,'Historical adjudication cannot override existing evidence') WHERE
    EXISTS(SELECT 1 FROM legacy_file_mappings WHERE store_kind='r2' AND provider='r2' AND object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM r2_upload_requests WHERE candidate_object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey')
      OR CASE WHEN json_valid(accepted_result_json) THEN json_extract(accepted_result_json,'$.key') END=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM metrology_reference_upload_requests WHERE candidate_object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey')
      OR CASE WHEN json_valid(accepted_result_json) THEN json_extract(accepted_result_json,'$.reference.assetKey') END=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM comment_item_acceptances WHERE candidate_object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey')
      OR CASE WHEN json_valid(accepted_result_json) THEN json_extract(accepted_result_json,'$.objectKey') END=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM imports WHERE client_request_id IS NOT NULL AND (workbook_asset_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey') OR manifest_asset_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey')))
    OR EXISTS(SELECT 1 FROM attachment_derivatives d JOIN assets a ON a.id=d.derived_asset_id WHERE a.r2_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM blob_gc_ledger WHERE store_kind='r2' AND provider='r2' AND object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM blob_integrity_quarantine WHERE store_kind='r2' AND provider='r2' AND object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey'))
    OR EXISTS(SELECT 1 FROM file_shadow_legacy_deletion_claims WHERE store_kind='r2' AND provider='r2' AND object_key=json_extract(NEW.request_json,'$.sourceLocator.objectKey'));
  SELECT RAISE(ABORT,'Historical adjudication baseline identity mismatch') WHERE
    json_extract(NEW.baseline_json,'$.baselineSha256') IS NOT json_extract(NEW.request_json,'$.expectedBaselineSha256')
    OR json_extract(NEW.baseline_json,'$.epoch') IS NOT json_extract(NEW.request_json,'$.expectedEpoch')
    OR json_extract(NEW.baseline_json,'$.head.occurrence_id') IS NOT NEW.occurrence_id
    OR json_extract(NEW.baseline_json,'$.head.generation') IS NOT json_extract(NEW.request_json,'$.generation')
    OR json_extract(NEW.baseline_json,'$.head.source_sha256') IS NOT json_extract(NEW.request_json,'$.sourceSha256')
    OR json_extract(NEW.baseline_json,'$.runtime.enabled') IS NOT 0
    OR json_extract(NEW.baseline_json,'$.runtime.incarnation') IS NOT json_extract(NEW.request_json,'$.expectedIncarnation');
  SELECT RAISE(ABORT,'Historical adjudication correction must extend its revoked chain') WHERE
    EXISTS(SELECT 1 FROM file_shadow_active_adjudications WHERE occurrence_id=NEW.occurrence_id)
    OR (NEW.supersedes_id IS NULL AND EXISTS(SELECT 1 FROM file_shadow_adjudications WHERE occurrence_id=NEW.occurrence_id))
    OR (NEW.supersedes_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM file_shadow_adjudications a
      JOIN file_shadow_adjudication_revocations r ON r.adjudication_id=a.id
      WHERE a.id=NEW.supersedes_id AND a.occurrence_id=NEW.occurrence_id AND julianday(NEW.created_at)>=julianday(r.created_at)
      AND NOT EXISTS(SELECT 1 FROM file_shadow_adjudications successor WHERE successor.supersedes_id=a.id)));
END;
CREATE TRIGGER file_shadow_adjudications_epoch AFTER INSERT ON file_shadow_adjudications BEGIN UPDATE file_shadow_control SET epoch=epoch+1 WHERE singleton=1; END;

CREATE TRIGGER file_shadow_adjudication_withdrawals_insert_guard BEFORE INSERT ON file_shadow_adjudication_withdrawals BEGIN
  SELECT RAISE(ABORT,'Invalid historical adjudication withdrawal') WHERE (((SELECT count(*) FROM json_each(NEW.request_json))=15 AND (SELECT count(*) FROM json_each(NEW.request_json) WHERE key IN('requestId','key','occurrenceId','generation','sourceSha256','sourceLocator','expectedBaselineSha256','expectedEpoch','expectedIncarnation','sourceProfile','purpose','purposeStatement','namespaceStatement','evidenceReference','supersedesId'))=15)
    AND ((typeof(json_extract(NEW.request_json,'$.requestId'))='text' AND length(json_extract(NEW.request_json,'$.requestId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.requestId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.requestId'))=36 AND json_extract(NEW.request_json,'$.requestId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.requestId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.requestId'),'-',''))=32) AND json_extract(NEW.request_json,'$.requestId') IS NEW.request_id
    AND (json_type(NEW.request_json,'$.key')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.key'))=4 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.key') WHERE key IN('consumerKind','consumerId','consumerSubId','fileSlot'))=4)
    AND json_extract(NEW.request_json,'$.key.consumerKind') IS 'project_content_attachment' AND json_extract(NEW.request_json,'$.key.fileSlot') IS 'primary' AND json_type(NEW.request_json,'$.key.consumerId') IS 'text' AND json_type(NEW.request_json,'$.key.consumerSubId') IS 'text' AND length(CAST(json_extract(NEW.request_json,'$.key') AS BLOB))<=65536
    AND (typeof(json_extract(NEW.request_json,'$.occurrenceId'))='text' AND length(json_extract(NEW.request_json,'$.occurrenceId')) BETWEEN 1 AND 256 AND instr(json_extract(NEW.request_json,'$.occurrenceId'),char(0))=0)
    AND json_type(NEW.request_json,'$.generation') IS 'integer' AND json_extract(NEW.request_json,'$.generation') BETWEEN 1 AND 9007199254740991
    AND (typeof(json_extract(NEW.request_json,'$.sourceSha256'))='text' AND length(json_extract(NEW.request_json,'$.sourceSha256'))=64 AND json_extract(NEW.request_json,'$.sourceSha256') NOT GLOB '*[^0-9a-f]*' AND instr(json_extract(NEW.request_json,'$.sourceSha256'),char(0))=0)
    AND (json_type(NEW.request_json,'$.sourceLocator')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceLocator'))=3 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceLocator') WHERE key IN('storeKind','provider','objectKey'))=3)
    AND json_extract(NEW.request_json,'$.sourceLocator.storeKind') IS 'r2' AND json_extract(NEW.request_json,'$.sourceLocator.provider') IS 'r2' AND (typeof(json_extract(NEW.request_json,'$.sourceLocator.objectKey'))='text' AND length(json_extract(NEW.request_json,'$.sourceLocator.objectKey')) BETWEEN 1 AND 4096 AND instr(json_extract(NEW.request_json,'$.sourceLocator.objectKey'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.sourceLocator.objectKey')))>0 AND length(CAST(json_extract(NEW.request_json,'$.sourceLocator.objectKey') AS BLOB))<=4096
    AND (typeof(json_extract(NEW.request_json,'$.expectedBaselineSha256'))='text' AND length(json_extract(NEW.request_json,'$.expectedBaselineSha256'))=64 AND json_extract(NEW.request_json,'$.expectedBaselineSha256') NOT GLOB '*[^0-9a-f]*' AND instr(json_extract(NEW.request_json,'$.expectedBaselineSha256'),char(0))=0)
    AND json_type(NEW.request_json,'$.expectedEpoch') IS 'integer' AND json_extract(NEW.request_json,'$.expectedEpoch') BETWEEN 0 AND 9007199254740991
    AND (json_type(NEW.request_json,'$.expectedIncarnation') IS 'null' OR ((typeof(json_extract(NEW.request_json,'$.expectedIncarnation'))='text' AND length(json_extract(NEW.request_json,'$.expectedIncarnation')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.expectedIncarnation'),char(0))=0) AND length(json_extract(NEW.request_json,'$.expectedIncarnation'))=36 AND json_extract(NEW.request_json,'$.expectedIncarnation') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.expectedIncarnation'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.expectedIncarnation'),'-',''))=32))
    AND (json_type(NEW.request_json,'$.sourceProfile')='object' AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceProfile'))=2 AND (SELECT count(*) FROM json_each(NEW.request_json,'$.sourceProfile') WHERE key IN('profileId','configurationRevision'))=2)
    AND (typeof(json_extract(NEW.request_json,'$.sourceProfile.profileId'))='text' AND length(json_extract(NEW.request_json,'$.sourceProfile.profileId')) BETWEEN 1 AND 256 AND instr(json_extract(NEW.request_json,'$.sourceProfile.profileId'),char(0))=0) AND json_type(NEW.request_json,'$.sourceProfile.configurationRevision') IS 'integer' AND json_extract(NEW.request_json,'$.sourceProfile.configurationRevision') IS 1
    AND json_extract(NEW.request_json,'$.purpose') IS 'research_source'
    AND ((typeof(json_extract(NEW.request_json,'$.purposeStatement'))='text' AND length(json_extract(NEW.request_json,'$.purposeStatement')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.purposeStatement'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.purposeStatement')))>0 AND length(CAST(json_extract(NEW.request_json,'$.purposeStatement') AS BLOB))<=16000)
    AND ((typeof(json_extract(NEW.request_json,'$.namespaceStatement'))='text' AND length(json_extract(NEW.request_json,'$.namespaceStatement')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.namespaceStatement'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.namespaceStatement')))>0 AND length(CAST(json_extract(NEW.request_json,'$.namespaceStatement') AS BLOB))<=16000)
    AND ((typeof(json_extract(NEW.request_json,'$.evidenceReference'))='text' AND length(json_extract(NEW.request_json,'$.evidenceReference')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.evidenceReference'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.evidenceReference')))>0 AND length(CAST(json_extract(NEW.request_json,'$.evidenceReference') AS BLOB))<=16000)
    AND (json_type(NEW.request_json,'$.supersedesId') IS 'null' OR (((typeof(json_extract(NEW.request_json,'$.supersedesId'))='text' AND length(json_extract(NEW.request_json,'$.supersedesId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.supersedesId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.supersedesId'))=36 AND json_extract(NEW.request_json,'$.supersedesId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.supersedesId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.supersedesId'),'-',''))=32) AND json_extract(NEW.request_json,'$.supersedesId') IS NOT json_extract(NEW.request_json,'$.requestId')))) IS NOT 1;
  SELECT RAISE(ABORT,'Historical adjudication already accepted') WHERE EXISTS(SELECT 1 FROM file_shadow_adjudications WHERE id=NEW.request_id);
END;
CREATE TRIGGER file_shadow_adjudication_revocations_insert_guard BEFORE INSERT ON file_shadow_adjudication_revocations BEGIN
  SELECT RAISE(ABORT,'Invalid historical adjudication revocation') WHERE (
    ((SELECT count(*) FROM json_each(NEW.request_json))=4 AND (SELECT count(*) FROM json_each(NEW.request_json) WHERE key IN('requestId','adjudicationId','adjudicationRequestSha256','reason'))=4)
    AND ((typeof(json_extract(NEW.request_json,'$.requestId'))='text' AND length(json_extract(NEW.request_json,'$.requestId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.requestId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.requestId'))=36 AND json_extract(NEW.request_json,'$.requestId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.requestId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.requestId'),'-',''))=32) AND json_extract(NEW.request_json,'$.requestId') IS NEW.id
    AND ((typeof(json_extract(NEW.request_json,'$.adjudicationId'))='text' AND length(json_extract(NEW.request_json,'$.adjudicationId')) BETWEEN 1 AND 36 AND instr(json_extract(NEW.request_json,'$.adjudicationId'),char(0))=0) AND length(json_extract(NEW.request_json,'$.adjudicationId'))=36 AND json_extract(NEW.request_json,'$.adjudicationId') GLOB '????????-????-4???-[89ab]???-????????????' AND replace(json_extract(NEW.request_json,'$.adjudicationId'),'-','') NOT GLOB '*[^0-9a-f]*' AND length(replace(json_extract(NEW.request_json,'$.adjudicationId'),'-',''))=32) AND json_extract(NEW.request_json,'$.adjudicationId') IS NEW.adjudication_id
    AND (typeof(json_extract(NEW.request_json,'$.adjudicationRequestSha256'))='text' AND length(json_extract(NEW.request_json,'$.adjudicationRequestSha256'))=64 AND json_extract(NEW.request_json,'$.adjudicationRequestSha256') NOT GLOB '*[^0-9a-f]*' AND instr(json_extract(NEW.request_json,'$.adjudicationRequestSha256'),char(0))=0) AND ((typeof(json_extract(NEW.request_json,'$.reason'))='text' AND length(json_extract(NEW.request_json,'$.reason')) BETWEEN 1 AND 4000 AND instr(json_extract(NEW.request_json,'$.reason'),char(0))=0) AND length(trim(json_extract(NEW.request_json,'$.reason')))>0 AND length(CAST(json_extract(NEW.request_json,'$.reason') AS BLOB))<=16000)
  ) IS NOT 1;
  SELECT RAISE(ABORT,'Historical adjudication revocation requires paused settled work') WHERE NOT EXISTS(SELECT 1 FROM file_authority_control c JOIN file_shadow_runtime_guard r ON r.singleton=c.singleton WHERE c.singleton=1 AND c.mode='overlap' AND r.enabled=0)
    OR NOT EXISTS(SELECT 1 FROM file_shadow_adjudications a WHERE a.id=NEW.adjudication_id AND a.request_sha256=json_extract(NEW.request_json,'$.adjudicationRequestSha256') AND julianday(NEW.created_at)>=julianday(a.created_at))
    OR EXISTS(SELECT 1 FROM file_shadow_operations o WHERE EXISTS(SELECT 1 FROM file_shadow_operation_adjudications b WHERE b.operation_id=o.id AND b.adjudication_id=NEW.adjudication_id) AND (o.status<>'cancelled'
    OR EXISTS(SELECT 1 FROM file_shadow_attempts a WHERE a.operation_id=o.id AND (a.write_started_at IS NOT NULL OR a.verified_at IS NOT NULL OR a.state NOT IN('failed','cancelled')))
    OR EXISTS(SELECT 1 FROM file_shadow_decisions d WHERE d.operation_id=o.id)));
END;
CREATE TRIGGER file_shadow_adjudication_revocations_epoch AFTER INSERT ON file_shadow_adjudication_revocations BEGIN UPDATE file_shadow_control SET epoch=epoch+1 WHERE singleton=1; END;

-- Copy admission is occurrence-scoped. Do not widen locator-global evidence.
DROP TRIGGER file_shadow_operations_insert_guard;
CREATE TRIGGER file_shadow_operations_insert_guard BEFORE INSERT ON file_shadow_operations BEGIN
  SELECT RAISE(ABORT,'Shadow operation requires a current frozen source generation and exact namespace') WHERE
    NOT EXISTS(SELECT 1 FROM file_authority_control WHERE singleton=1 AND mode='overlap') OR NEW.status<>'pending'
    OR EXISTS(SELECT 1 FROM file_shadow_decisions d WHERE d.occurrence_id=NEW.occurrence_id)
    OR NEW.captured_epoch<>(SELECT epoch FROM file_shadow_control WHERE singleton=1)
    OR NOT EXISTS(SELECT 1 FROM file_shadow_heads h JOIN file_shadow_occurrences o ON o.id=h.occurrence_id
      WHERE o.id=NEW.occurrence_id AND h.present=1 AND o.legacy_store_kind IS NEW.source_store_kind
      AND o.legacy_provider IS NEW.source_provider AND o.legacy_object_key IS NEW.source_object_key)
    OR (NEW.source_profile_id IS NOT NULL AND NOT (
      (EXISTS(SELECT 1 FROM file_shadow_namespace_evidence e WHERE e.store_kind IS NEW.source_store_kind AND e.provider IS NEW.source_provider
        AND e.object_key IS NEW.source_object_key AND e.storage_profile_id IS NEW.source_profile_id AND e.configuration_revision IS NEW.source_profile_revision)
       AND NOT EXISTS(SELECT 1 FROM file_shadow_namespace_evidence e WHERE e.store_kind IS NEW.source_store_kind AND e.provider IS NEW.source_provider
        AND e.object_key IS NEW.source_object_key AND (e.storage_profile_id IS NOT NEW.source_profile_id OR e.configuration_revision IS NOT NEW.source_profile_revision)))
      OR EXISTS(SELECT 1 FROM file_shadow_active_adjudications a JOIN file_shadow_heads h ON h.occurrence_id=a.occurrence_id AND h.present=1 AND h.source_json=a.source_json
    WHERE a.occurrence_id=NEW.occurrence_id
    AND NEW.purpose='research_source' AND NEW.source_store_kind='r2' AND NEW.source_provider='r2'
    AND NEW.source_object_key=json_extract(a.request_json,'$.sourceLocator.objectKey')
    AND NEW.source_profile_id=json_extract(a.request_json,'$.sourceProfile.profileId') AND NEW.source_profile_revision=json_extract(a.request_json,'$.sourceProfile.configurationRevision')
    AND NEW.source_expected_byte_size=a.source_expected_byte_size AND NEW.source_expected_sha256=a.source_expected_sha256
    AND EXISTS(SELECT 1 FROM storage_profiles p JOIN storage_profile_runtime r ON r.storage_profile_id=p.id WHERE p.id=NEW.source_profile_id AND p.adapter_type='r2' AND p.configuration_revision=NEW.source_profile_revision AND r.state IN('read_only','read_write')))
    ));
  -- An existing overlay cannot be bypassed with a NULL source profile or purpose.
  SELECT RAISE(ABORT,'Shadow operation contradicts its occurrence adjudication') WHERE
    EXISTS(SELECT 1 FROM file_shadow_active_adjudications a JOIN file_shadow_heads h ON h.occurrence_id=a.occurrence_id AND h.present=1 AND h.source_json=a.source_json WHERE a.occurrence_id=NEW.occurrence_id)
    AND NOT EXISTS(SELECT 1 FROM file_shadow_active_adjudications a JOIN file_shadow_heads h ON h.occurrence_id=a.occurrence_id AND h.present=1 AND h.source_json=a.source_json
    WHERE a.occurrence_id=NEW.occurrence_id
    AND NEW.purpose='research_source' AND NEW.source_store_kind='r2' AND NEW.source_provider='r2'
    AND NEW.source_object_key=json_extract(a.request_json,'$.sourceLocator.objectKey')
    AND NEW.source_profile_id=json_extract(a.request_json,'$.sourceProfile.profileId') AND NEW.source_profile_revision=json_extract(a.request_json,'$.sourceProfile.configurationRevision')
    AND NEW.source_expected_byte_size=a.source_expected_byte_size AND NEW.source_expected_sha256=a.source_expected_sha256
    AND EXISTS(SELECT 1 FROM storage_profiles p JOIN storage_profile_runtime r ON r.storage_profile_id=p.id WHERE p.id=NEW.source_profile_id AND p.adapter_type='r2' AND p.configuration_revision=NEW.source_profile_revision AND r.state IN('read_only','read_write')));
END;
CREATE TRIGGER file_shadow_operations_capture_adjudication AFTER INSERT ON file_shadow_operations BEGIN
  INSERT INTO file_shadow_operation_adjudications(operation_id,adjudication_id,adjudication_request_sha256)
    SELECT NEW.id,a.id,a.request_sha256 FROM file_shadow_active_adjudications a
    JOIN file_shadow_heads h ON h.occurrence_id=a.occurrence_id AND h.present=1 AND h.source_json=a.source_json
    WHERE a.occurrence_id=NEW.occurrence_id;
END;
CREATE TRIGGER file_shadow_operation_adjudications_insert_guard BEFORE INSERT ON file_shadow_operation_adjudications BEGIN
  SELECT RAISE(ABORT,'Shadow operation adjudication binding mismatch') WHERE NOT EXISTS(
    SELECT 1 FROM file_shadow_operations o JOIN file_shadow_active_adjudications a ON a.id=NEW.adjudication_id
    JOIN file_shadow_heads h ON h.occurrence_id=a.occurrence_id AND h.present=1 AND h.source_json=a.source_json
    WHERE o.id=NEW.operation_id AND o.status='pending' AND o.occurrence_id=a.occurrence_id AND a.request_sha256=NEW.adjudication_request_sha256
    AND o.captured_epoch=(SELECT epoch FROM file_shadow_control WHERE singleton=1)
    AND o.purpose='research_source' AND o.source_store_kind='r2' AND o.source_provider='r2'
    AND o.source_object_key=json_extract(a.request_json,'$.sourceLocator.objectKey')
    AND o.source_profile_id=json_extract(a.request_json,'$.sourceProfile.profileId')
    AND o.source_profile_revision=json_extract(a.request_json,'$.sourceProfile.configurationRevision')
    AND o.source_expected_sha256=a.source_expected_sha256 AND o.source_expected_byte_size=a.source_expected_byte_size);
END;

-- Historical statements only connect EXISTING roots to physical aliases. Their
-- own presence never creates retention. Revocation cannot release an old hold.
CREATE VIEW file_shadow_retention_namespaces AS SELECT * FROM file_shadow_namespace_evidence
  UNION SELECT 'r2','r2',json_extract(request_json,'$.sourceLocator.objectKey'),
    json_extract(request_json,'$.sourceProfile.profileId'),json_extract(request_json,'$.sourceProfile.configurationRevision')
  FROM file_shadow_adjudications;

DROP VIEW file_shadow_legacy_retention_edges;
CREATE VIEW file_shadow_legacy_retention_edges AS SELECT h.store_kind,h.provider,h.object_key,NULL AS blob_record_id,'file_shadow_operation' AS source_type,h.operation_id AS source_id,'file_shadow_hold' AS occurrence_type,h.id AS occurrence_id,'shadow_source_hold' AS retention_reason,NULL AS retain_until FROM file_shadow_legacy_holds h WHERE h.released_at IS NULL
UNION ALL SELECT e.store_kind,e.provider,e.object_key,NULL,'file_location',h.location_id,'file_location_hold',h.id,h.hold_kind,h.expires_at FROM file_location_holds h JOIN file_locations l ON l.id=h.location_id JOIN file_shadow_retention_namespaces e ON e.storage_profile_id=l.storage_profile_id AND e.object_key=l.object_key WHERE h.released_at IS NULL AND(h.expires_at IS NULL OR julianday(h.expires_at)>julianday('now'))
UNION ALL SELECT m.store_kind,m.provider,m.object_key,NULL,'file',h.file_id,'file_hold',h.id,h.hold_kind,h.expires_at FROM file_holds h JOIN legacy_file_mappings m ON m.file_id=h.file_id WHERE h.released_at IS NULL AND(h.expires_at IS NULL OR julianday(h.expires_at)>julianday('now'))
UNION ALL SELECT e.store_kind,e.provider,e.object_key,NULL,'file_shadow_occurrence',h.occurrence_id,'file_shadow_publication',h.occurrence_id,'shadow_publication',NULL FROM file_shadow_heads h JOIN file_shadow_decisions d ON d.occurrence_id=h.occurrence_id JOIN file_publications p ON p.file_id=d.file_id AND p.state='ready' JOIN file_locations l ON l.id=p.active_location_id JOIN file_shadow_retention_namespaces e ON e.storage_profile_id=l.storage_profile_id AND e.object_key=l.object_key WHERE h.present=1 AND d.decision='resolved';

DROP TRIGGER file_shadow_location_hold_legacy_guard;
CREATE TRIGGER file_shadow_location_hold_legacy_guard BEFORE INSERT ON file_location_holds BEGIN SELECT RAISE(ABORT,'Location hold cannot cross legacy deletion') WHERE EXISTS(SELECT 1 FROM file_locations l JOIN file_shadow_retention_namespaces e ON e.storage_profile_id=l.storage_profile_id AND e.object_key=l.object_key JOIN file_shadow_legacy_deletion_claims g ON g.store_kind=e.store_kind AND g.provider=e.provider AND g.object_key=e.object_key WHERE l.id=NEW.location_id); END;

CREATE TRIGGER file_shadow_adjudication_generation_complete BEFORE DELETE ON file_shadow_runtime_guard BEGIN SELECT RAISE(ABORT,'V17 adjudication runtime gate cannot be deleted'); END;
