/** Closed portable FP4 history catalog; installation grants are never serialized. */
export const RESEARCH_PACKAGE_EXPORT_COLUMNS = {
  "research_package_source_identity": [
    "singleton",
    "installation_id"
  ],
  "research_package_jobs": [
    "id",
    "request_id",
    "actor",
    "kind",
    "input_json",
    "package_id",
    "source_installation_id",
    "source_upload_job_id",
    "package_digest",
    "destination_scope",
    "copy_identity",
    "accepted_at",
    "target_policy_json",
    "domain_plan_json",
    "frozen_archive_json",
    "state",
    "phase",
    "generation",
    "owner_token",
    "runtime_incarnation",
    "lease_expires_at",
    "actor_checked_at",
    "updated_at",
    "result_json",
    "reason",
    "expires_at"
  ],
  "research_package_requests": [
    "actor",
    "request_id",
    "input_json",
    "job_id",
    "accepted_at",
    "reused"
  ],
  "research_package_records": [
    "job_id",
    "record_kind",
    "source_id",
    "record_json",
    "ordinal"
  ],
  "research_package_files": [
    "job_id",
    "logical_file_id",
    "entry_kind",
    "purpose",
    "byte_size",
    "sha256",
    "archive_path",
    "alias_original_name",
    "alias_created_at",
    "media_type",
    "source_file_id",
    "source_alias_id",
    "source_location_id",
    "source_profile_id",
    "source_profile_revision",
    "source_namespace",
    "source_object_key",
    "hold_operation_id",
    "target_profile_id",
    "target_profile_revision",
    "target_namespace",
    "target_policy_revision",
    "candidate_file_id",
    "candidate_asset_id",
    "archive_entry_json",
    "reuse_file_id",
    "reuse_location_id",
    "reuse_asset_id",
    "state",
    "result_file_id",
    "result_location_id",
    "updated_at",
    "reason"
  ],
  "research_package_attempts": [
    "id",
    "job_id",
    "logical_file_id",
    "file_id",
    "location_id",
    "object_key",
    "owner_token",
    "generation",
    "runtime_incarnation",
    "state",
    "created_at",
    "write_started_at",
    "io_settled_at",
    "verified_byte_size",
    "verified_sha256",
    "verified_at",
    "verified_owner_token",
    "verified_generation",
    "verified_runtime_incarnation",
    "updated_at",
    "reason"
  ],
  "research_package_identity_maps": [
    "job_id",
    "entity_kind",
    "source_id",
    "destination_id"
  ]
} as const;
export const RESEARCH_PACKAGE_LOCAL_TABLE_NAMES = ["system_research_package_cleanup_grants"] as const;
