/** Portable FP3 history, separate from installation execution admission. */
export const FILE_JOBS_EXPORT_COLUMNS = {
  "file_migration_jobs": [
    "id",
    "request_id",
    "actor",
    "input_json",
    "target_profile_id",
    "target_configuration_revision",
    "target_namespace",
    "accepted_at",
    "state",
    "generation",
    "owner_token",
    "runtime_incarnation",
    "lease_expires_at",
    "admin_checked_at",
    "updated_at",
    "reason"
  ],
  "file_migration_items": [
    "job_id",
    "file_id",
    "purpose",
    "source_location_id",
    "source_profile_id",
    "source_configuration_revision",
    "source_namespace",
    "source_object_key",
    "byte_size",
    "sha256",
    "hold_operation_id",
    "state",
    "destination_location_id",
    "updated_at",
    "reason",
    "cleanup_requested_at",
    "cleanup_actor",
    "cleanup_not_before",
    "cleanup_released_at"
  ],
  "file_migration_attempts": [
    "id",
    "job_id",
    "file_id",
    "location_id",
    "object_key",
    "owner_token",
    "generation",
    "runtime_incarnation",
    "state",
    "created_at",
    "write_started_at",
    "io_settled_at",
    "verified_byte_size",
    "verified_sha256",
    "verified_at",
    "verified_owner_token",
    "verified_generation",
    "verified_runtime_incarnation",
    "updated_at",
    "reason"
  ]
} as const;
export const FILE_JOBS_LOCAL_TABLE_NAMES = ["file_job_runtime_guard", "file_job_cleanup_grants"] as const;
