// Generated by scripts/generate-portable-runtime-schema.mjs from reviewed, hash-pinned migrations.
// Current checkpoint only; frozen V1/V19–V24 catalogs are unchanged. Uploaded SQL never supplies target DDL.
import type { RecoveryTableSpec } from "./system-recovery-image";
import type { ExportSchemaObject } from "./export";
export const PORTABLE_RUNTIME_CHECKPOINT_ID = "portable-runtime/v25";
export const PORTABLE_RUNTIME_RECOVERY_SCHEMA_SHA256 = "f325f0ce87b8ce0e700853f17fd3e05401d476c1e6468fa32b3a73f867906ad3";
// Separate conservative lexical comparison for actual split-migration observations; raw catalog pins above stay unchanged.
export const PORTABLE_RUNTIME_RECOVERY_LEXICAL_SCHEMA_SHA256 = "5288070fe00db3d7ea6b5b04f235e1a0ed2b716a51ae87b155fd609d60249907";
export const PORTABLE_RUNTIME_RECOVERY_TABLES: readonly (RecoveryTableSpec & { classification: "content" | "protected_configuration" | "protected_identity" | "local" })[] = [
  {
    "name": "assets",
    "columns": [
      "id",
      "import_id",
      "r2_key",
      "original_name",
      "mime_type",
      "byte_size",
      "status",
      "sha256",
      "actor_email",
      "created_at",
      "file_id",
      "storage_profile_id",
      "storage_profile_revision",
      "object_key"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "attachment_derivatives",
    "columns": [
      "id",
      "source_sha256",
      "source_byte_size",
      "derivative_kind",
      "generator_version",
      "derived_asset_id",
      "status",
      "error_code",
      "retain_until",
      "actor_email",
      "created_at",
      "updated_at",
      "derived_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "blob_gc_ledger",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "blob_record_id",
      "state",
      "operation_id",
      "orphaned_at",
      "deletion_started_at",
      "deleted_at",
      "attempt_count",
      "last_error",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "blob_integrity_quarantine",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "blob_record_id",
      "reason",
      "expected_byte_size",
      "observed_byte_size",
      "operation_id",
      "detected_at",
      "last_checked_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "comment_item_acceptances",
    "columns": [
      "item_id",
      "submission_id",
      "actor_email",
      "purpose",
      "expected_sha256",
      "expected_byte_size",
      "storage_profile_id",
      "storage_profile_revision",
      "candidate_blob_id",
      "candidate_object_key",
      "execution_token",
      "started_at",
      "status",
      "accepted_result_json",
      "created_at",
      "role_selection_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "item_id"
    ]
  },
  {
    "name": "comment_submission_acceptances",
    "columns": [
      "submission_id",
      "actor_email",
      "operation_id",
      "request_sha256",
      "request_input_json",
      "publication_plan_json",
      "request_scope",
      "storage_policy_revision",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "storage_role_policy_revision",
      "role_selection_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "submission_id"
    ]
  },
  {
    "name": "comment_submission_items",
    "columns": [
      "id",
      "submission_id",
      "kind",
      "status",
      "position",
      "filename",
      "mime_type",
      "byte_size",
      "original_filename",
      "original_mime_type",
      "original_byte_size",
      "title",
      "description",
      "external_url",
      "asset_id",
      "storage_object_id",
      "sha256",
      "related_item_id",
      "error_message",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "comment_submission_targets",
    "columns": [
      "submission_id",
      "sample_id",
      "run_id",
      "run_step_id",
      "expected_updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "submission_id",
      "run_step_id"
    ]
  },
  {
    "name": "comment_submissions",
    "columns": [
      "id",
      "context_kind",
      "sample_id",
      "scope",
      "body",
      "status",
      "error_message",
      "actor_email",
      "created_at",
      "updated_at",
      "completed_at",
      "cancelled_at",
      "deleted_at",
      "deleted_by",
      "last_mutation_id",
      "deletion_operation_id",
      "retry_until",
      "retry_closed_at",
      "retry_closed_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "events",
    "columns": [
      "id",
      "sample_id",
      "kind",
      "body",
      "asset_key",
      "metadata_json",
      "actor_email",
      "created_at",
      "asset_file_id",
      "thumbnail_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_acceptance_candidates",
    "columns": [
      "acceptance_kind",
      "acceptance_id",
      "item_id",
      "purpose",
      "access_scope",
      "storage_profile_id",
      "expected_byte_size",
      "expected_sha256",
      "candidate_file_id",
      "candidate_location_id",
      "candidate_object_key",
      "state",
      "result_file_id",
      "result_location_id",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "acceptance_kind",
      "acceptance_id",
      "item_id"
    ]
  },
  {
    "name": "file_authority_control",
    "columns": [
      "singleton",
      "mode",
      "revision",
      "updated_at",
      "activated_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_authority_runtime_guard",
    "columns": [
      "singleton",
      "incarnation",
      "enabled",
      "enabled_by",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_consumer_migration_decisions",
    "columns": [
      "id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "decision",
      "file_id",
      "reason",
      "source_row_sha256",
      "legacy_store_kind",
      "legacy_provider",
      "legacy_object_key",
      "legacy_location_id",
      "operation_id",
      "evidence_json",
      "decided_by",
      "decided_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_derivations",
    "columns": [
      "id",
      "source_file_id",
      "derived_file_id",
      "generator",
      "generator_version",
      "parameters_sha256",
      "trust_state",
      "source_verified_sha256",
      "derived_verified_sha256",
      "verification_operation_id",
      "evidence_json",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_holds",
    "columns": [
      "id",
      "file_id",
      "hold_kind",
      "operation_id",
      "reason",
      "acquired_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_job_cleanup_grants",
    "columns": [
      "job_id",
      "runtime_incarnation",
      "requested_at",
      "actor"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id"
    ]
  },
  {
    "name": "file_job_runtime_guard",
    "columns": [
      "singleton",
      "enabled",
      "incarnation",
      "last_heartbeat_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_location_gc_ledger",
    "columns": [
      "location_id",
      "state",
      "operation_id",
      "orphaned_at",
      "deletion_started_at",
      "deleted_at",
      "attempt_count",
      "last_error",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_location_holds",
    "columns": [
      "id",
      "location_id",
      "hold_kind",
      "operation_id",
      "reason",
      "acquired_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_location_integrity_quarantine",
    "columns": [
      "location_id",
      "reason",
      "expected_byte_size",
      "observed_byte_size",
      "expected_sha256",
      "observed_sha256",
      "operation_id",
      "detected_at",
      "last_checked_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_location_publications",
    "columns": [
      "location_id",
      "file_id",
      "storage_profile_id",
      "object_key",
      "verified_byte_size",
      "verified_sha256",
      "verification_method",
      "verification_operation_id",
      "verified_at",
      "published_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_locations",
    "columns": [
      "id",
      "file_id",
      "storage_profile_id",
      "object_key",
      "state",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_migration_attempts",
    "columns": [
      "id",
      "job_id",
      "file_id",
      "location_id",
      "object_key",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "state",
      "created_at",
      "write_started_at",
      "io_settled_at",
      "verified_byte_size",
      "verified_sha256",
      "verified_at",
      "verified_owner_token",
      "verified_generation",
      "verified_runtime_incarnation",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_migration_items",
    "columns": [
      "job_id",
      "file_id",
      "purpose",
      "source_location_id",
      "source_profile_id",
      "source_configuration_revision",
      "source_namespace",
      "source_object_key",
      "byte_size",
      "sha256",
      "hold_operation_id",
      "state",
      "destination_location_id",
      "updated_at",
      "reason",
      "cleanup_requested_at",
      "cleanup_actor",
      "cleanup_not_before",
      "cleanup_released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "file_id"
    ]
  },
  {
    "name": "file_migration_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "input_json",
      "target_profile_id",
      "target_configuration_revision",
      "target_namespace",
      "accepted_at",
      "state",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "admin_checked_at",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_publications",
    "columns": [
      "file_id",
      "purpose",
      "access_scope",
      "verified_byte_size",
      "verified_sha256",
      "active_location_id",
      "state",
      "published_at",
      "retired_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "file_id"
    ]
  },
  {
    "name": "file_registry_rowid_claims",
    "columns": [
      "registry_name",
      "claimed_rowid"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "registry_name",
      "claimed_rowid"
    ]
  },
  {
    "name": "file_shadow_adjudication_revocations",
    "columns": [
      "id",
      "adjudication_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_adjudication_withdrawals",
    "columns": [
      "request_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "request_id"
    ]
  },
  {
    "name": "file_shadow_adjudications",
    "columns": [
      "id",
      "occurrence_id",
      "supersedes_id",
      "request_json",
      "request_sha256",
      "source_json",
      "baseline_json",
      "source_expected_byte_size",
      "source_expected_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_attempts",
    "columns": [
      "id",
      "operation_id",
      "attempt_number",
      "owner_token",
      "runtime_incarnation",
      "candidate_file_id",
      "candidate_location_id",
      "candidate_object_key",
      "verified_byte_size",
      "verified_sha256",
      "source_verified_at",
      "state",
      "lease_expires_at",
      "created_at",
      "write_started_at",
      "verified_at",
      "completed_at",
      "last_error"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_checkpoints",
    "columns": [
      "id",
      "captured_epoch",
      "current_count",
      "resolved_count",
      "unresolved_count",
      "pending_count",
      "captured_by",
      "captured_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_closures",
    "columns": [
      "occurrence_id",
      "successor_occurrence_id",
      "closed_epoch",
      "closed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "occurrence_id"
    ]
  },
  {
    "name": "file_shadow_control",
    "columns": [
      "singleton",
      "epoch"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_decisions",
    "columns": [
      "occurrence_id",
      "operation_id",
      "decision",
      "file_id",
      "location_id",
      "baseline_sha256",
      "reason",
      "decided_by",
      "decided_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "occurrence_id"
    ]
  },
  {
    "name": "file_shadow_dependency_versions",
    "columns": [
      "dependency_kind",
      "dependency_key",
      "revision",
      "present",
      "snapshot_json"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "dependency_kind",
      "dependency_key",
      "revision"
    ]
  },
  {
    "name": "file_shadow_enablements",
    "columns": [
      "singleton",
      "expected_epoch",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_heads",
    "columns": [
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "generation",
      "occurrence_id",
      "present",
      "source_rowid",
      "source_json",
      "observed_epoch"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot"
    ]
  },
  {
    "name": "file_shadow_legacy_deletion_claims",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "first_state",
      "operation_id",
      "observed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "file_shadow_legacy_holds",
    "columns": [
      "id",
      "operation_id",
      "store_kind",
      "provider",
      "object_key",
      "storage_profile_id",
      "profile_revision",
      "acquired_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_occurrences",
    "columns": [
      "id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "generation",
      "present",
      "source_rowid",
      "source_json",
      "legacy_store_kind",
      "legacy_provider",
      "legacy_object_key",
      "expected_purpose",
      "observed_epoch",
      "observed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_operation_adjudications",
    "columns": [
      "operation_id",
      "adjudication_id",
      "adjudication_request_sha256"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "file_shadow_operations",
    "columns": [
      "id",
      "occurrence_id",
      "captured_epoch",
      "baseline_sha256",
      "purpose",
      "access_scope",
      "source_store_kind",
      "source_provider",
      "source_object_key",
      "source_profile_id",
      "source_profile_revision",
      "source_expected_byte_size",
      "source_expected_sha256",
      "destination_profile_id",
      "destination_profile_revision",
      "status",
      "created_by",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_profile_enablements",
    "columns": [
      "storage_profile_id",
      "configuration_revision",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "file_shadow_reconciliations",
    "columns": [
      "id",
      "attempt_id",
      "runtime_incarnation",
      "verified_epoch",
      "verified_byte_size",
      "verified_sha256",
      "source_verified_at",
      "destination_verified_at",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_runtime_guard",
    "columns": [
      "singleton",
      "incarnation",
      "enabled",
      "enabled_by",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_runtime_incarnations",
    "columns": [
      "incarnation",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "incarnation"
    ]
  },
  {
    "name": "file_shadow_withdrawals",
    "columns": [
      "operation_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "files",
    "columns": [
      "id",
      "purpose",
      "access_scope",
      "expected_byte_size",
      "expected_sha256",
      "verified_sha256",
      "state",
      "active_location_id",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "import_file_acceptances",
    "columns": [
      "import_id",
      "item_id",
      "purpose",
      "storage_profile_id",
      "storage_profile_revision",
      "role_policy_revision",
      "expected_sha256",
      "expected_byte_size",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "result_file_id",
      "result_location_id",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "import_id",
      "item_id"
    ]
  },
  {
    "name": "imports",
    "columns": [
      "id",
      "status",
      "source_filename",
      "source_sha256",
      "sheet_name",
      "template_type",
      "recipe_family_id",
      "template_version_id",
      "workbook_asset_key",
      "manifest_asset_key",
      "warning_count",
      "error_message",
      "actor_email",
      "created_at",
      "completed_at",
      "operation_id",
      "lease_expires_at",
      "finalization_id",
      "recovery_operation_id",
      "client_request_id",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "accepted_result_json",
      "workbook_file_id",
      "manifest_file_id",
      "file_targets_protocol",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "legacy_file_mappings",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "file_id",
      "location_id",
      "classification",
      "evidence_json",
      "observed_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "local_accounts",
    "columns": [
      "principal_id",
      "username",
      "password_verifier",
      "credential_revision",
      "enabled",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_identity",
    "primaryKeyColumns": [
      "principal_id"
    ]
  },
  {
    "name": "local_admin_grants",
    "columns": [
      "principal_id",
      "granted_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "principal_id"
    ]
  },
  {
    "name": "local_auth_events",
    "columns": [
      "sequence",
      "principal_id",
      "kind",
      "happened_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_identity",
    "primaryKeyColumns": [
      "sequence"
    ]
  },
  {
    "name": "local_identity_installation",
    "columns": [
      "singleton",
      "bootstrap_principal_id",
      "catalog_id",
      "initialized_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "local_login_throttle",
    "columns": [
      "bucket_hash",
      "window_started_at",
      "attempts"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "bucket_hash"
    ]
  },
  {
    "name": "local_sessions",
    "columns": [
      "token_hash",
      "principal_id",
      "credential_revision",
      "created_at",
      "absolute_expires_at",
      "last_seen_at",
      "revoked_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "token_hash"
    ]
  },
  {
    "name": "managed_storage_objects",
    "columns": [
      "id",
      "provider",
      "object_key",
      "original_name",
      "mime_type",
      "byte_size",
      "sha256",
      "status",
      "actor_email",
      "created_at",
      "orphaned_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "metrology_reference_upload_requests",
    "columns": [
      "id",
      "actor_email",
      "client_request_id",
      "operation_id",
      "template_version_id",
      "candidate_reference_id",
      "publication_plan_json",
      "ingress",
      "purpose",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "metrology_template_references",
    "columns": [
      "id",
      "template_version_id",
      "asset_id",
      "display_name",
      "position",
      "actor_email",
      "created_at",
      "deleted_at",
      "deleted_by",
      "superseded_by_occurrence_id",
      "superseded_at",
      "superseded_by",
      "supersession_operation_id",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_content_attachments",
    "columns": [
      "project_content_id",
      "asset_id",
      "storage_object_id",
      "original_name",
      "mime_type",
      "byte_size",
      "created_by",
      "created_at",
      "creation_operation_id",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "project_content_id"
    ]
  },
  {
    "name": "project_contents",
    "columns": [
      "id",
      "project_id",
      "content_type",
      "markdown_source",
      "attachment_caption",
      "attachment_source_url",
      "format_version",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_edges",
    "columns": [
      "id",
      "project_id",
      "source_item_id",
      "target_item_id",
      "source_handle",
      "target_handle",
      "marker_start",
      "marker_end",
      "label",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_items",
    "columns": [
      "id",
      "project_id",
      "item_type",
      "project_content_id",
      "reference_target_id",
      "created_sequence",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_map_placements",
    "columns": [
      "id",
      "project_item_id",
      "x",
      "y",
      "width",
      "height",
      "z_index",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "projects",
    "columns": [
      "id",
      "title",
      "revision",
      "next_created_sequence",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "r2_upload_requests",
    "columns": [
      "id",
      "actor_email",
      "client_request_id",
      "operation_id",
      "ingress",
      "purpose",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recipe_change_proposals",
    "columns": [
      "id",
      "recipe_family_id",
      "source_template_version_id",
      "source_verification_id",
      "change_type",
      "body",
      "status",
      "actor_email",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recipe_families",
    "columns": [
      "id",
      "name",
      "template_type",
      "created_by",
      "created_at",
      "archived_at",
      "archived_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recovery_file_alias_evidence",
    "columns": [
      "evidence_id",
      "table_name",
      "alias_id",
      "original_json",
      "destination_file_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "evidence_id",
      "table_name",
      "alias_id"
    ]
  },
  {
    "name": "recovery_file_binding_evidence",
    "columns": [
      "evidence_id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "purpose",
      "source_file_id",
      "row_sha256",
      "preview_origin_json"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "evidence_id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot"
    ]
  },
  {
    "name": "recovery_file_evidence",
    "columns": [
      "id",
      "backup_id",
      "source_image_sha256",
      "destination_metadata_sha256",
      "source_locator_json",
      "source_file_id",
      "destination_file_id",
      "location_id",
      "profile_id",
      "profile_revision",
      "namespace_identity",
      "object_key",
      "purpose",
      "byte_size",
      "sha256",
      "verification_operation_id",
      "verified_at",
      "published_at",
      "producer_trust",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "reference_targets",
    "columns": [
      "id",
      "registry_version",
      "target_type",
      "target_id",
      "first_registered_at",
      "last_validated_at",
      "tombstoned_at",
      "last_known_contexts_json"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_attempts",
    "columns": [
      "id",
      "job_id",
      "logical_file_id",
      "file_id",
      "location_id",
      "object_key",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "state",
      "created_at",
      "write_started_at",
      "io_settled_at",
      "verified_byte_size",
      "verified_sha256",
      "verified_at",
      "verified_owner_token",
      "verified_generation",
      "verified_runtime_incarnation",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_files",
    "columns": [
      "job_id",
      "logical_file_id",
      "entry_kind",
      "purpose",
      "byte_size",
      "sha256",
      "archive_path",
      "alias_original_name",
      "alias_created_at",
      "media_type",
      "source_file_id",
      "source_alias_id",
      "source_location_id",
      "source_profile_id",
      "source_profile_revision",
      "source_namespace",
      "source_object_key",
      "hold_operation_id",
      "target_profile_id",
      "target_profile_revision",
      "target_namespace",
      "target_policy_revision",
      "candidate_file_id",
      "candidate_asset_id",
      "archive_entry_json",
      "reuse_file_id",
      "reuse_location_id",
      "reuse_asset_id",
      "state",
      "result_file_id",
      "result_location_id",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "logical_file_id"
    ]
  },
  {
    "name": "research_package_identity_maps",
    "columns": [
      "job_id",
      "entity_kind",
      "source_id",
      "destination_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "entity_kind",
      "source_id"
    ]
  },
  {
    "name": "research_package_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "kind",
      "input_json",
      "package_id",
      "source_installation_id",
      "source_upload_job_id",
      "package_digest",
      "destination_scope",
      "copy_identity",
      "accepted_at",
      "target_policy_json",
      "domain_plan_json",
      "frozen_archive_json",
      "state",
      "phase",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "actor_checked_at",
      "updated_at",
      "result_json",
      "reason",
      "expires_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_records",
    "columns": [
      "job_id",
      "record_kind",
      "source_id",
      "record_json",
      "ordinal"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "record_kind",
      "source_id"
    ]
  },
  {
    "name": "research_package_requests",
    "columns": [
      "actor",
      "request_id",
      "input_json",
      "job_id",
      "accepted_at",
      "reused"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "actor",
      "request_id"
    ]
  },
  {
    "name": "research_package_source_identity",
    "columns": [
      "singleton",
      "installation_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "run_plan_revisions",
    "columns": [
      "id",
      "run_id",
      "revision_no",
      "template_version_id",
      "effective_after_step_id",
      "reason",
      "actor_email",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_assets",
    "columns": [
      "id",
      "run_step_id",
      "asset_id",
      "role",
      "position",
      "actor_email",
      "created_at",
      "deleted_at",
      "deleted_by",
      "last_mutation_id",
      "superseded_by_occurrence_id",
      "superseded_at",
      "superseded_by",
      "supersession_operation_id",
      "filename",
      "mime_type",
      "byte_size",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_comments",
    "columns": [
      "id",
      "run_step_id",
      "scope",
      "operation_group_id",
      "asset_id",
      "actor_email",
      "created_at",
      "submission_id",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "asset_deleted_at",
      "asset_deleted_by",
      "last_mutation_id",
      "deletion_operation_id",
      "asset_deletion_operation_id",
      "legacy_body",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_plan_links",
    "columns": [
      "run_plan_revision_id",
      "template_step_id",
      "run_step_id",
      "relation",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "run_plan_revision_id",
      "template_step_id",
      "run_step_id"
    ]
  },
  {
    "name": "run_steps",
    "columns": [
      "id",
      "run_id",
      "previous_step_id",
      "position",
      "origin",
      "plan_status",
      "template_step_id",
      "logical_step_key",
      "definition_hash",
      "expected_state_hash",
      "title",
      "status",
      "notes",
      "tool_name",
      "parameters_text",
      "comments_text",
      "deviation_note",
      "actualized_at",
      "created_at",
      "updated_by",
      "last_mutation_id",
      "updated_at",
      "entry_kind",
      "deleted_at",
      "deleted_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "runs",
    "columns": [
      "id",
      "sample_id",
      "recipe_family_id",
      "template_version_id",
      "current_plan_revision_id",
      "predecessor_run_id",
      "anchor_step_id",
      "sequence_no",
      "run_group_id",
      "template_name_snapshot",
      "template_type_snapshot",
      "template_version_snapshot",
      "status",
      "created_by",
      "created_at",
      "completed_at",
      "initial_state_hash",
      "run_kind",
      "deleted_at",
      "deleted_by",
      "last_mutation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "samples",
    "columns": [
      "id",
      "code",
      "title",
      "description",
      "status",
      "location",
      "parent_id",
      "pinned",
      "created_by",
      "updated_by",
      "last_mutation_id",
      "created_at",
      "updated_at",
      "inherited_state_hash",
      "deleted_at",
      "deleted_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "state_representation_assets",
    "columns": [
      "state_hash",
      "asset_id",
      "position",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "state_hash",
      "asset_id"
    ]
  },
  {
    "name": "state_representations",
    "columns": [
      "hash",
      "hash_scheme",
      "representation_type",
      "logical_state_key",
      "content_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "hash"
    ]
  },
  {
    "name": "state_verification_steps",
    "columns": [
      "verification_id",
      "run_step_id",
      "ordinal"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "verification_id",
      "run_step_id"
    ]
  },
  {
    "name": "state_verifications",
    "columns": [
      "id",
      "sample_id",
      "after_run_step_id",
      "previous_verification_id",
      "run_plan_revision_id",
      "expected_state_hash",
      "result",
      "evidence_asset_id",
      "note",
      "status",
      "actor_email",
      "created_at",
      "evidence_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "step_definitions",
    "columns": [
      "hash",
      "hash_scheme",
      "name",
      "tool_name",
      "parameters_text",
      "comments_text",
      "canonical_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "hash"
    ]
  },
  {
    "name": "storage_profile_activations",
    "columns": [
      "operation_id",
      "storage_profile_id",
      "configuration_revision",
      "action",
      "candidate_profile_id",
      "candidate_revision",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "binding_revision",
      "actor",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "storage_profile_admissions",
    "columns": [
      "operation_id",
      "native_profile_id",
      "candidate_profile_id",
      "candidate_revision",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "actor",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "storage_profile_runtime",
    "columns": [
      "storage_profile_id",
      "state",
      "registered_at",
      "activated_at",
      "retired_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "storage_profiles",
    "columns": [
      "id",
      "adapter_type",
      "namespace_identity",
      "configuration_source",
      "credential_reference",
      "configuration_revision",
      "state",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "storage_role_defaults",
    "columns": [
      "role",
      "storage_profile_id",
      "storage_profile_revision",
      "policy_revision",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "role"
    ]
  },
  {
    "name": "storage_role_policy_revisions",
    "columns": [
      "policy_revision",
      "role",
      "storage_profile_id",
      "storage_profile_revision",
      "operation_id",
      "actor",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "policy_revision",
      "role"
    ]
  },
  {
    "name": "system_recovery_attempts",
    "columns": [
      "id",
      "job_id",
      "generation",
      "runtime_incarnation",
      "owner_token",
      "object_key",
      "expected_byte_size",
      "expected_sha256",
      "state",
      "created_at",
      "settled_at",
      "verified_at",
      "cleaned_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_recovery_files",
    "columns": [
      "job_id",
      "id",
      "ordinal",
      "outcome",
      "file_json"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "id"
    ]
  },
  {
    "name": "system_recovery_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "kind",
      "state",
      "phase",
      "input_json",
      "accepted_at",
      "updated_at",
      "reason",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "source_upload_job_id",
      "target_id",
      "target_incarnation",
      "checkpoint_json",
      "source_checkpoint",
      "artifact_key",
      "archive_byte_size",
      "archive_sha256",
      "expires_at",
      "completed_files",
      "total_files",
      "bytes_done",
      "bytes_total",
      "result_json"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_recovery_legacy_holds",
    "columns": [
      "job_id",
      "store_kind",
      "provider",
      "object_key",
      "released_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "system_recovery_maintenance",
    "columns": [
      "singleton",
      "state",
      "generation",
      "token",
      "requested_by",
      "backup_job_id",
      "checkpoint_sha256",
      "started_at",
      "fenced_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_maintenance_requests",
    "columns": [
      "request_id",
      "actor",
      "action",
      "expected_generation",
      "result_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "request_id"
    ]
  },
  {
    "name": "system_recovery_metadata_chunks",
    "columns": [
      "job_id",
      "name",
      "ordinal",
      "chunk"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "name",
      "ordinal"
    ]
  },
  {
    "name": "system_recovery_requests",
    "columns": [
      "request_id",
      "actor",
      "job_id",
      "input_sha256",
      "accepted_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "actor",
      "request_id"
    ]
  },
  {
    "name": "system_recovery_runtime",
    "columns": [
      "singleton",
      "enabled",
      "incarnation",
      "installation_id",
      "last_heartbeat_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_target_claim",
    "columns": [
      "singleton",
      "target_id",
      "job_id",
      "incarnation",
      "challenge",
      "schema_sha256",
      "image_sha256",
      "status",
      "cursor_json",
      "verified_at",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "lease_expires_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_target_files",
    "columns": [
      "job_id",
      "logical_id",
      "source_blob_id",
      "file_id",
      "location_id",
      "profile_id",
      "namespace",
      "object_key",
      "purpose",
      "byte_size",
      "sha256",
      "state",
      "owner_token",
      "generation",
      "incarnation",
      "verified_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "logical_id"
    ]
  },
  {
    "name": "system_recovery_target_provenance",
    "columns": [
      "job_id",
      "ordinal",
      "image_sha256",
      "chunk",
      "created_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "ordinal"
    ]
  },
  {
    "name": "system_recovery_write_leases",
    "columns": [
      "id",
      "owner",
      "kind",
      "generation",
      "created_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_research_package_cleanup_grants",
    "columns": [
      "job_id",
      "runtime_incarnation",
      "requested_at",
      "actor",
      "mode"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id"
    ]
  },
  {
    "name": "system_storage_candidate_check_audit",
    "columns": [
      "id",
      "check_id",
      "operation",
      "execution_token",
      "actor",
      "status",
      "write_outcome",
      "read_outcome",
      "metadata_outcome",
      "delete_outcome",
      "cleanup_outcome",
      "result_code",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_candidate_checks",
    "columns": [
      "id",
      "profile_id",
      "configuration_revision",
      "credential_ref",
      "envelope_revision",
      "namespace_json",
      "namespace_sha256",
      "configuration_sha256",
      "envelope_version",
      "key_id",
      "nonce",
      "ciphertext",
      "probe_key",
      "payload_sha256",
      "payload_size",
      "requested_by",
      "created_at",
      "execution_kind",
      "execution_token",
      "execution_deadline",
      "execution_actor",
      "status",
      "write_outcome",
      "read_outcome",
      "metadata_outcome",
      "delete_outcome",
      "cleanup_outcome",
      "result_code",
      "updated_at",
      "completed_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_configuration_audit",
    "columns": [
      "id",
      "profile_id",
      "configuration_revision",
      "actor",
      "operation",
      "outcome",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_configuration_revisions",
    "columns": [
      "profile_id",
      "revision",
      "label",
      "namespace_json",
      "credential_ref",
      "created_at",
      "created_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "profile_id",
      "revision"
    ]
  },
  {
    "name": "system_storage_credential_descriptors",
    "columns": [
      "credential_ref",
      "profile_id",
      "configuration_revision",
      "namespace_sha256",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "credential_ref"
    ]
  },
  {
    "name": "system_storage_credential_payloads",
    "columns": [
      "credential_ref",
      "envelope_revision",
      "envelope_version",
      "key_id",
      "nonce",
      "ciphertext"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "credential_ref"
    ]
  },
  {
    "name": "system_storage_credential_reenvelopes",
    "columns": [
      "operation_id",
      "profile_id",
      "configuration_revision",
      "credential_ref",
      "previous_envelope_revision",
      "envelope_revision",
      "outcome",
      "previous_key_id",
      "key_id",
      "created_at",
      "created_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "system_storage_native_bindings",
    "columns": [
      "storage_profile_id",
      "candidate_profile_id",
      "candidate_revision",
      "credential_ref",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "activation_operation_id",
      "binding_revision",
      "created_at",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "system_storage_profiles",
    "columns": [
      "id",
      "adapter_type",
      "namespace_json",
      "namespace_sha256",
      "latest_revision",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "template_steps",
    "columns": [
      "id",
      "template_version_id",
      "logical_step_key",
      "position",
      "source_row",
      "step_number",
      "section_name",
      "definition_hash",
      "expected_state_hash",
      "raw_json"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "template_versions",
    "columns": [
      "id",
      "recipe_family_id",
      "name",
      "template_type",
      "version",
      "manifest_hash",
      "initial_state_hash",
      "source_filename",
      "source_asset_key",
      "content_json",
      "created_by",
      "created_at",
      "locked_at",
      "locked_by",
      "archived_at",
      "archived_by",
      "template_kind",
      "metrology_notes",
      "deleted_at",
      "deleted_by",
      "source_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  }
];
export const PORTABLE_RUNTIME_RECOVERY_MIGRATIONS = [
  {
    "name": "0001_v3_baseline.sql",
    "sha256": "da244690cc17e88c99628461e4c4d5b52db37334b7fd6dd04643dfa7ebe4b4d2",
    "appliedToFreshSchema": true
  },
  {
    "name": "0002_fp1_file_registry.sql",
    "sha256": "28f95dbc7fca4a824c38575ec6be998aacf0d50f25c7325ea745a5a2362d5584",
    "appliedToFreshSchema": true
  },
  {
    "name": "0003_fp1_import_acceptance.sql",
    "sha256": "c56596cb35bbadda16e8be14f8b3527a1b7384947be1a68c7604602a3d42c701",
    "appliedToFreshSchema": true
  },
  {
    "name": "0004_r2_upload_acceptance.sql",
    "sha256": "911adba4ba3c5fa6f9e560d72f337da8669cc17be4d51e470940bb86fb62c1b8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0005_metrology_reference_acceptance.sql",
    "sha256": "ddda77389c39d71d9475c0f83b04995616a8940f00be83eee27b1e9efd4bcd5e",
    "appliedToFreshSchema": true
  },
  {
    "name": "0006_comment_acceptance.sql",
    "sha256": "5f5a6354f1c55b95644fcd010631a949ba7fdb55f8c77ded7a1829be2b745de8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0007_fp1_file_authority_transition.sql",
    "sha256": "252123f4e901f2c6ae970f84c25fe34d9ef3f3433fcc144ca583c70b4556218d",
    "appliedToFreshSchema": true
  },
  {
    "name": "0008_fp1_shadow_runtime.sql",
    "sha256": "324ab0ec3ce282f13b7ee0caae1be1977d817bbd448836925090b72709bd2dfc",
    "appliedToFreshSchema": true
  },
  {
    "name": "0009_fp1_shadow_withdrawals.sql",
    "sha256": "8394abf5853cb3217da8c5d5b2b1b29188f1f0100d90b8fdc9b569c8621283f8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0010_fp1_shadow_adjudications.sql",
    "sha256": "6038d51909b8d2fa8ad1d1d3eba4bd96808bb7d4b9a42fafeaeb10b36d40a1a0",
    "appliedToFreshSchema": true
  },
  {
    "name": "0011_fp1_retire_legacy_test_projects.sql",
    "sha256": "177d3e751bb066dec3b1fcfe78f90703f24f8817b45ce8a6ee861b6d86b6011a",
    "appliedToFreshSchema": false
  },
  {
    "name": "0012_fp1_file_authority_runtime.sql",
    "sha256": "8360b65ae1f9b199f90e88443bde82e49bb6db6cc9f9110c8bc4410b51a92fab",
    "appliedToFreshSchema": true
  },
  {
    "name": "0013_fp1_r2_role_defaults.sql",
    "sha256": "d5df0455221af4b52b007a7462b48355fdc5fc6471766979696c2545b19a2343",
    "appliedToFreshSchema": true
  },
  {
    "name": "0014_fp2_storage_configuration.sql",
    "sha256": "427f022d84086aa29ac34a3b0540e70807fc68e3815e2db98312614028e00d54",
    "appliedToFreshSchema": true
  },
  {
    "name": "0015_fp2_storage_candidate_checks.sql",
    "sha256": "f2558f69ea77c6382e44f705e76fcc2ed56ad320274c43a3ad0be0afa8cc40c3",
    "appliedToFreshSchema": true
  },
  {
    "name": "0016_fp2_credential_reenvelopes.sql",
    "sha256": "6b622eaa0fccca4b241a803bcb3b0ee19688d432648d28eb80f34b0afffc36c3",
    "appliedToFreshSchema": true
  },
  {
    "name": "0017_fp2_native_storage_profiles.sql",
    "sha256": "94919cde4b666e6243358ee328bdc53f7572dbbb5f42ae9a4a4f94dc5a7e4057",
    "appliedToFreshSchema": true
  },
  {
    "name": "0018_fp2_native_file_runtime.sql",
    "sha256": "76a72e55cd0cadaf48ccedf559cdd411ba26e93096578cdd99fce9c89ab0fe6d",
    "appliedToFreshSchema": true
  },
  {
    "name": "0019_fp3_file_jobs.sql",
    "sha256": "23d216a71383b4238a9dbf73e98e0252173ba94c1af13b2892e0eb798e4d19a4",
    "appliedToFreshSchema": true
  },
  {
    "name": "0020_fp4_research_packages.sql",
    "sha256": "0dc7a2248a06a434cf92ca7f647bab4c50ad7f6419c792d10ec13b05b94c44b4",
    "appliedToFreshSchema": true
  },
  {
    "name": "0021_fp5_system_recovery.sql",
    "sha256": "834df694d90705962b6a8d81e97b0c1cf9b4514ff270f954e29d2080b596a3e1",
    "appliedToFreshSchema": true
  },
  {
    "name": "0022_fp5_recovery_evidence.sql",
    "sha256": "b637e7e901168e11276b76040cd0a1c45693884a35ad35b5279527e54609ee48",
    "appliedToFreshSchema": true
  },
  {
    "name": "0023_portable_local_identity.sql",
    "sha256": "7d16acea4506c080397bf57ba3f103cb128a5e4fdfca333a321e99f881dfc245",
    "appliedToFreshSchema": true
  }
] as const;
// Exact native SQLite-owned application inventory, retained for historical business fingerprint projection.
// It contributes to neither the canonical application nor paired Node checkpoint digest.
export const PORTABLE_RUNTIME_INTERNAL_SCHEMA_OBJECTS: readonly ExportSchemaObject[] = [
  {
    "type": "index",
    "name": "sqlite_autoindex_assets_1",
    "tableName": "assets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_assets_2",
    "tableName": "assets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_attachment_derivatives_1",
    "tableName": "attachment_derivatives",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_blob_gc_ledger_1",
    "tableName": "blob_gc_ledger",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_blob_integrity_quarantine_1",
    "tableName": "blob_integrity_quarantine",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_item_acceptances_1",
    "tableName": "comment_item_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_item_acceptances_2",
    "tableName": "comment_item_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_item_acceptances_3",
    "tableName": "comment_item_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_item_acceptances_4",
    "tableName": "comment_item_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submission_acceptances_1",
    "tableName": "comment_submission_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submission_acceptances_2",
    "tableName": "comment_submission_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submission_items_1",
    "tableName": "comment_submission_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submission_items_2",
    "tableName": "comment_submission_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submission_targets_1",
    "tableName": "comment_submission_targets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_comment_submissions_1",
    "tableName": "comment_submissions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_events_1",
    "tableName": "events",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_acceptance_candidates_1",
    "tableName": "file_acceptance_candidates",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_acceptance_candidates_2",
    "tableName": "file_acceptance_candidates",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_consumer_migration_decisions_2",
    "tableName": "file_consumer_migration_decisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_derivations_2",
    "tableName": "file_derivations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_holds_2",
    "tableName": "file_holds",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_location_holds_2",
    "tableName": "file_location_holds",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_location_publications_2",
    "tableName": "file_location_publications",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_location_publications_3",
    "tableName": "file_location_publications",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_locations_1",
    "tableName": "file_locations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_locations_2",
    "tableName": "file_locations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_locations_3",
    "tableName": "file_locations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_migration_attempts_2",
    "tableName": "file_migration_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_migration_attempts_3",
    "tableName": "file_migration_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_migration_items_1",
    "tableName": "file_migration_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_migration_jobs_2",
    "tableName": "file_migration_jobs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_publications_2",
    "tableName": "file_publications",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_adjudication_revocations_2",
    "tableName": "file_shadow_adjudication_revocations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_adjudications_2",
    "tableName": "file_shadow_adjudications",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_attempts_2",
    "tableName": "file_shadow_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_attempts_3",
    "tableName": "file_shadow_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_attempts_4",
    "tableName": "file_shadow_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_closures_2",
    "tableName": "file_shadow_closures",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_decisions_2",
    "tableName": "file_shadow_decisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_heads_1",
    "tableName": "file_shadow_heads",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_legacy_holds_2",
    "tableName": "file_shadow_legacy_holds",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_occurrences_2",
    "tableName": "file_shadow_occurrences",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_file_shadow_reconciliations_2",
    "tableName": "file_shadow_reconciliations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_files_1",
    "tableName": "files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_import_file_acceptances_1",
    "tableName": "import_file_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_import_file_acceptances_3",
    "tableName": "import_file_acceptances",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_imports_1",
    "tableName": "imports",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_legacy_file_mappings_1",
    "tableName": "legacy_file_mappings",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_legacy_file_mappings_2",
    "tableName": "legacy_file_mappings",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_legacy_file_mappings_3",
    "tableName": "legacy_file_mappings",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_accounts_1",
    "tableName": "local_accounts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_accounts_2",
    "tableName": "local_accounts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_admin_grants_1",
    "tableName": "local_admin_grants",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_identity_installation_1",
    "tableName": "local_identity_installation",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_login_throttle_1",
    "tableName": "local_login_throttle",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_local_sessions_1",
    "tableName": "local_sessions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_managed_storage_objects_1",
    "tableName": "managed_storage_objects",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_managed_storage_objects_2",
    "tableName": "managed_storage_objects",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_1",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_2",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_3",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_4",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_5",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_reference_upload_requests_6",
    "tableName": "metrology_reference_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_template_references_1",
    "tableName": "metrology_template_references",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_metrology_template_references_2",
    "tableName": "metrology_template_references",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_content_attachments_1",
    "tableName": "project_content_attachments",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_contents_1",
    "tableName": "project_contents",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_edges_1",
    "tableName": "project_edges",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_items_1",
    "tableName": "project_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_items_2",
    "tableName": "project_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_items_3",
    "tableName": "project_items",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_map_placements_1",
    "tableName": "project_map_placements",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_project_map_placements_2",
    "tableName": "project_map_placements",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_projects_1",
    "tableName": "projects",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_r2_upload_requests_1",
    "tableName": "r2_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_r2_upload_requests_2",
    "tableName": "r2_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_r2_upload_requests_3",
    "tableName": "r2_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_r2_upload_requests_4",
    "tableName": "r2_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_r2_upload_requests_5",
    "tableName": "r2_upload_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_recipe_change_proposals_1",
    "tableName": "recipe_change_proposals",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_recipe_families_1",
    "tableName": "recipe_families",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_recipe_families_2",
    "tableName": "recipe_families",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_recovery_file_evidence_2",
    "tableName": "recovery_file_evidence",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_recovery_file_evidence_3",
    "tableName": "recovery_file_evidence",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_reference_targets_1",
    "tableName": "reference_targets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_reference_targets_2",
    "tableName": "reference_targets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_attempts_2",
    "tableName": "research_package_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_attempts_3",
    "tableName": "research_package_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_files_1",
    "tableName": "research_package_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_files_3",
    "tableName": "research_package_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_identity_maps_2",
    "tableName": "research_package_identity_maps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_research_package_jobs_2",
    "tableName": "research_package_jobs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_plan_revisions_1",
    "tableName": "run_plan_revisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_plan_revisions_2",
    "tableName": "run_plan_revisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_step_assets_1",
    "tableName": "run_step_assets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_step_assets_2",
    "tableName": "run_step_assets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_step_comments_1",
    "tableName": "run_step_comments",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_step_plan_links_1",
    "tableName": "run_step_plan_links",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_steps_1",
    "tableName": "run_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_run_steps_2",
    "tableName": "run_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_runs_1",
    "tableName": "runs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_runs_2",
    "tableName": "runs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_samples_1",
    "tableName": "samples",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_samples_2",
    "tableName": "samples",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_state_representation_assets_1",
    "tableName": "state_representation_assets",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_state_representations_1",
    "tableName": "state_representations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_state_verification_steps_1",
    "tableName": "state_verification_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_state_verifications_1",
    "tableName": "state_verifications",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_step_definitions_1",
    "tableName": "step_definitions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_storage_profile_activations_1",
    "tableName": "storage_profile_activations",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_storage_profile_admissions_2",
    "tableName": "storage_profile_admissions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_storage_profiles_1",
    "tableName": "storage_profiles",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_storage_profiles_2",
    "tableName": "storage_profiles",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_storage_role_policy_revisions_2",
    "tableName": "storage_role_policy_revisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_attempts_1",
    "tableName": "system_recovery_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_attempts_2",
    "tableName": "system_recovery_attempts",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_files_1",
    "tableName": "system_recovery_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_files_2",
    "tableName": "system_recovery_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_jobs_1",
    "tableName": "system_recovery_jobs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_jobs_2",
    "tableName": "system_recovery_jobs",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_legacy_holds_1",
    "tableName": "system_recovery_legacy_holds",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_maintenance_requests_1",
    "tableName": "system_recovery_maintenance_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_metadata_chunks_1",
    "tableName": "system_recovery_metadata_chunks",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_requests_1",
    "tableName": "system_recovery_requests",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_target_files_1",
    "tableName": "system_recovery_target_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_target_files_2",
    "tableName": "system_recovery_target_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_target_files_3",
    "tableName": "system_recovery_target_files",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_target_provenance_1",
    "tableName": "system_recovery_target_provenance",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_recovery_write_leases_1",
    "tableName": "system_recovery_write_leases",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_candidate_checks_1",
    "tableName": "system_storage_candidate_checks",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_candidate_checks_2",
    "tableName": "system_storage_candidate_checks",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_configuration_audit_1",
    "tableName": "system_storage_configuration_audit",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_configuration_revisions_1",
    "tableName": "system_storage_configuration_revisions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_credential_descriptors_1",
    "tableName": "system_storage_credential_descriptors",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_credential_descriptors_2",
    "tableName": "system_storage_credential_descriptors",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_credential_payloads_1",
    "tableName": "system_storage_credential_payloads",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_credential_reenvelopes_1",
    "tableName": "system_storage_credential_reenvelopes",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_profiles_1",
    "tableName": "system_storage_profiles",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_profiles_2",
    "tableName": "system_storage_profiles",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_system_storage_profiles_3",
    "tableName": "system_storage_profiles",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_steps_1",
    "tableName": "template_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_steps_2",
    "tableName": "template_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_steps_3",
    "tableName": "template_steps",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_versions_1",
    "tableName": "template_versions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_versions_2",
    "tableName": "template_versions",
    "sql": null
  },
  {
    "type": "index",
    "name": "sqlite_autoindex_template_versions_3",
    "tableName": "template_versions",
    "sql": null
  }
];
// These paired Node digests include exactly the separately admitted platform ledgers.
export const PORTABLE_NODE_CHECKPOINT_SCHEMA_SHA256: Readonly<Record<string, string>> = Object.freeze({
  "installation/empty": "735420514cf33dcf89178f684b551bfee176870538938a9c519ce91a88e4fbec",
  "migration/0001_v3_baseline.sql": "306256b7bf5b7da704cdaa86b9f930b657f886b7436fa85ebeb0eb3450ca93ed",
  "migration/0002_fp1_file_registry.sql": "cb6ac6beb50521ed15fd5a64c578740f2d406bb2eb0ac5b43b2d8f150925c725",
  "migration/0003_fp1_import_acceptance.sql": "42b777fa2055d7d78a4f70912e7879daf23e9db3c1c35c46af9f82c3c42fbb32",
  "migration/0004_r2_upload_acceptance.sql": "8032facb33158bccc319912112517e9779a9304d90d3ddb488129af056bd941f",
  "migration/0005_metrology_reference_acceptance.sql": "992aeb1a7bf88d3d0e248e91ad9c4d76c52bafabe95df590c3f5f07b229ce3f1",
  "migration/0006_comment_acceptance.sql": "87f1d45dbbda9878618ed579bf8c45a1908efbfb3acb652c2eb735712eb09267",
  "migration/0007_fp1_file_authority_transition.sql": "d11600d440d25577a6e4309daf8fca4791ce7136fcb57e8a242e1dbd423a6690",
  "migration/0008_fp1_shadow_runtime.sql": "36e9b1588c979e4a5e2608b51c82318ac360b8bdf22f287868c93828e516129d",
  "migration/0009_fp1_shadow_withdrawals.sql": "1972ef5a87a671ce4144a893c5c0d1872e7d7cfe28ef09669373cb6c26002a5b",
  "migration/0010_fp1_shadow_adjudications.sql": "e14ca402f7b4cf53321b51c505f309d2855a75dc4c84f7e4a1236bce0d8b3eb1",
  "migration/0011_fp1_retire_legacy_test_projects.sql": "e14ca402f7b4cf53321b51c505f309d2855a75dc4c84f7e4a1236bce0d8b3eb1",
  "migration/0012_fp1_file_authority_runtime.sql": "6498ee706f41666909077c88566f20bc79a80f055fcb6436dccfc082b34e7ac9",
  "migration/0013_fp1_r2_role_defaults.sql": "ed36298ec8659f3a2885dd6515da5657f834e7699cba949b3dd7132aae1c98ef",
  "migration/0014_fp2_storage_configuration.sql": "ca89b758a14cc6c30ffcfc23c25c449c96843274962c235a41f28ccc2b858edb",
  "migration/0015_fp2_storage_candidate_checks.sql": "be29e7c7f6191d796852ee9b5c6e688d46aeeb19deaf84f5dd9b5b2357ac87ff",
  "migration/0016_fp2_credential_reenvelopes.sql": "32178c264def1f4966e6445d17c8d9e3cfd7a847a00ff57b816c5dd1a693ec8b",
  "migration/0017_fp2_native_storage_profiles.sql": "b8badae00481f2c14b5e0aa6b676d2683c57b063bae20a3b1ae4e29bc5d94858",
  "migration/0018_fp2_native_file_runtime.sql": "83d2b6486e7008aa455816770139251f8c8a48d1320bb8d6d4b13534a5496759",
  "migration/0019_fp3_file_jobs.sql": "652449c05d3c33afa0b1bc964225558a7f78b933dee21a6180bd586a755d581c",
  "migration/0020_fp4_research_packages.sql": "3e4445e418fade6ae5b589d49a06b99b78a2634dd459c9df3089f61051a8903d",
  "migration/0021_fp5_system_recovery.sql": "3d0c293cb9c8d1804a2353d306731a413b5a2391b945bae8e27fb8eb45452f27",
  "migration/0022_fp5_recovery_evidence.sql": "ba8b5e7f5b3b31fcc064c0aeda0dc050da665d17f52ff925bda9f0529091e3c3",
  "portable-runtime/v25": "d861d4522cd498c834fbe8c17b3b1c7562ed619a7bceaf6c3cddca3bf18ab793"
});
