// Generated by scripts/generate-system-recovery-schema.mjs from reviewed repository migrations.
// Uploaded archive SQL never supplies target DDL.
import type { RecoveryTableSpec } from "./system-recovery-image";
export const RECOVERY_SCHEMA_SHA256 = "7783c42f0259f6b9b857a0e2860d4c754638faaa8e13500a4cd9ab953555f3d8";
export const RECOVERY_TABLES: readonly (RecoveryTableSpec & { classification: "content" | "protected_configuration" | "local" })[] = [
  {
    "name": "assets",
    "columns": [
      "id",
      "import_id",
      "r2_key",
      "original_name",
      "mime_type",
      "byte_size",
      "status",
      "sha256",
      "actor_email",
      "created_at",
      "file_id",
      "storage_profile_id",
      "storage_profile_revision",
      "object_key"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "attachment_derivatives",
    "columns": [
      "id",
      "source_sha256",
      "source_byte_size",
      "derivative_kind",
      "generator_version",
      "derived_asset_id",
      "status",
      "error_code",
      "retain_until",
      "actor_email",
      "created_at",
      "updated_at",
      "derived_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "blob_gc_ledger",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "blob_record_id",
      "state",
      "operation_id",
      "orphaned_at",
      "deletion_started_at",
      "deleted_at",
      "attempt_count",
      "last_error",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "blob_integrity_quarantine",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "blob_record_id",
      "reason",
      "expected_byte_size",
      "observed_byte_size",
      "operation_id",
      "detected_at",
      "last_checked_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "comment_item_acceptances",
    "columns": [
      "item_id",
      "submission_id",
      "actor_email",
      "purpose",
      "expected_sha256",
      "expected_byte_size",
      "storage_profile_id",
      "storage_profile_revision",
      "candidate_blob_id",
      "candidate_object_key",
      "execution_token",
      "started_at",
      "status",
      "accepted_result_json",
      "created_at",
      "role_selection_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "item_id"
    ]
  },
  {
    "name": "comment_submission_acceptances",
    "columns": [
      "submission_id",
      "actor_email",
      "operation_id",
      "request_sha256",
      "request_input_json",
      "publication_plan_json",
      "request_scope",
      "storage_policy_revision",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "storage_role_policy_revision",
      "role_selection_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "submission_id"
    ]
  },
  {
    "name": "comment_submission_items",
    "columns": [
      "id",
      "submission_id",
      "kind",
      "status",
      "position",
      "filename",
      "mime_type",
      "byte_size",
      "original_filename",
      "original_mime_type",
      "original_byte_size",
      "title",
      "description",
      "external_url",
      "asset_id",
      "storage_object_id",
      "sha256",
      "related_item_id",
      "error_message",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "comment_submission_targets",
    "columns": [
      "submission_id",
      "sample_id",
      "run_id",
      "run_step_id",
      "expected_updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "submission_id",
      "run_step_id"
    ]
  },
  {
    "name": "comment_submissions",
    "columns": [
      "id",
      "context_kind",
      "sample_id",
      "scope",
      "body",
      "status",
      "error_message",
      "actor_email",
      "created_at",
      "updated_at",
      "completed_at",
      "cancelled_at",
      "deleted_at",
      "deleted_by",
      "last_mutation_id",
      "deletion_operation_id",
      "retry_until",
      "retry_closed_at",
      "retry_closed_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "events",
    "columns": [
      "id",
      "sample_id",
      "kind",
      "body",
      "asset_key",
      "metadata_json",
      "actor_email",
      "created_at",
      "asset_file_id",
      "thumbnail_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_acceptance_candidates",
    "columns": [
      "acceptance_kind",
      "acceptance_id",
      "item_id",
      "purpose",
      "access_scope",
      "storage_profile_id",
      "expected_byte_size",
      "expected_sha256",
      "candidate_file_id",
      "candidate_location_id",
      "candidate_object_key",
      "state",
      "result_file_id",
      "result_location_id",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "acceptance_kind",
      "acceptance_id",
      "item_id"
    ]
  },
  {
    "name": "file_authority_control",
    "columns": [
      "singleton",
      "mode",
      "revision",
      "updated_at",
      "activated_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_authority_runtime_guard",
    "columns": [
      "singleton",
      "incarnation",
      "enabled",
      "enabled_by",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_consumer_migration_decisions",
    "columns": [
      "id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "decision",
      "file_id",
      "reason",
      "source_row_sha256",
      "legacy_store_kind",
      "legacy_provider",
      "legacy_object_key",
      "legacy_location_id",
      "operation_id",
      "evidence_json",
      "decided_by",
      "decided_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_derivations",
    "columns": [
      "id",
      "source_file_id",
      "derived_file_id",
      "generator",
      "generator_version",
      "parameters_sha256",
      "trust_state",
      "source_verified_sha256",
      "derived_verified_sha256",
      "verification_operation_id",
      "evidence_json",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_holds",
    "columns": [
      "id",
      "file_id",
      "hold_kind",
      "operation_id",
      "reason",
      "acquired_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_job_cleanup_grants",
    "columns": [
      "job_id",
      "runtime_incarnation",
      "requested_at",
      "actor"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id"
    ]
  },
  {
    "name": "file_job_runtime_guard",
    "columns": [
      "singleton",
      "enabled",
      "incarnation",
      "last_heartbeat_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_location_gc_ledger",
    "columns": [
      "location_id",
      "state",
      "operation_id",
      "orphaned_at",
      "deletion_started_at",
      "deleted_at",
      "attempt_count",
      "last_error",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_location_holds",
    "columns": [
      "id",
      "location_id",
      "hold_kind",
      "operation_id",
      "reason",
      "acquired_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_location_integrity_quarantine",
    "columns": [
      "location_id",
      "reason",
      "expected_byte_size",
      "observed_byte_size",
      "expected_sha256",
      "observed_sha256",
      "operation_id",
      "detected_at",
      "last_checked_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_location_publications",
    "columns": [
      "location_id",
      "file_id",
      "storage_profile_id",
      "object_key",
      "verified_byte_size",
      "verified_sha256",
      "verification_method",
      "verification_operation_id",
      "verified_at",
      "published_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "location_id"
    ]
  },
  {
    "name": "file_locations",
    "columns": [
      "id",
      "file_id",
      "storage_profile_id",
      "object_key",
      "state",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_migration_attempts",
    "columns": [
      "id",
      "job_id",
      "file_id",
      "location_id",
      "object_key",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "state",
      "created_at",
      "write_started_at",
      "io_settled_at",
      "verified_byte_size",
      "verified_sha256",
      "verified_at",
      "verified_owner_token",
      "verified_generation",
      "verified_runtime_incarnation",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_migration_items",
    "columns": [
      "job_id",
      "file_id",
      "purpose",
      "source_location_id",
      "source_profile_id",
      "source_configuration_revision",
      "source_namespace",
      "source_object_key",
      "byte_size",
      "sha256",
      "hold_operation_id",
      "state",
      "destination_location_id",
      "updated_at",
      "reason",
      "cleanup_requested_at",
      "cleanup_actor",
      "cleanup_not_before",
      "cleanup_released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "file_id"
    ]
  },
  {
    "name": "file_migration_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "input_json",
      "target_profile_id",
      "target_configuration_revision",
      "target_namespace",
      "accepted_at",
      "state",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "admin_checked_at",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_publications",
    "columns": [
      "file_id",
      "purpose",
      "access_scope",
      "verified_byte_size",
      "verified_sha256",
      "active_location_id",
      "state",
      "published_at",
      "retired_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "file_id"
    ]
  },
  {
    "name": "file_registry_rowid_claims",
    "columns": [
      "registry_name",
      "claimed_rowid"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "registry_name",
      "claimed_rowid"
    ]
  },
  {
    "name": "file_shadow_adjudication_revocations",
    "columns": [
      "id",
      "adjudication_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_adjudication_withdrawals",
    "columns": [
      "request_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "request_id"
    ]
  },
  {
    "name": "file_shadow_adjudications",
    "columns": [
      "id",
      "occurrence_id",
      "supersedes_id",
      "request_json",
      "request_sha256",
      "source_json",
      "baseline_json",
      "source_expected_byte_size",
      "source_expected_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_attempts",
    "columns": [
      "id",
      "operation_id",
      "attempt_number",
      "owner_token",
      "runtime_incarnation",
      "candidate_file_id",
      "candidate_location_id",
      "candidate_object_key",
      "verified_byte_size",
      "verified_sha256",
      "source_verified_at",
      "state",
      "lease_expires_at",
      "created_at",
      "write_started_at",
      "verified_at",
      "completed_at",
      "last_error"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_checkpoints",
    "columns": [
      "id",
      "captured_epoch",
      "current_count",
      "resolved_count",
      "unresolved_count",
      "pending_count",
      "captured_by",
      "captured_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_closures",
    "columns": [
      "occurrence_id",
      "successor_occurrence_id",
      "closed_epoch",
      "closed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "occurrence_id"
    ]
  },
  {
    "name": "file_shadow_control",
    "columns": [
      "singleton",
      "epoch"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_decisions",
    "columns": [
      "occurrence_id",
      "operation_id",
      "decision",
      "file_id",
      "location_id",
      "baseline_sha256",
      "reason",
      "decided_by",
      "decided_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "occurrence_id"
    ]
  },
  {
    "name": "file_shadow_dependency_versions",
    "columns": [
      "dependency_kind",
      "dependency_key",
      "revision",
      "present",
      "snapshot_json"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "dependency_kind",
      "dependency_key",
      "revision"
    ]
  },
  {
    "name": "file_shadow_enablements",
    "columns": [
      "singleton",
      "expected_epoch",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_heads",
    "columns": [
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "generation",
      "occurrence_id",
      "present",
      "source_rowid",
      "source_json",
      "observed_epoch"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot"
    ]
  },
  {
    "name": "file_shadow_legacy_deletion_claims",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "first_state",
      "operation_id",
      "observed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "file_shadow_legacy_holds",
    "columns": [
      "id",
      "operation_id",
      "store_kind",
      "provider",
      "object_key",
      "storage_profile_id",
      "profile_revision",
      "acquired_at",
      "released_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_occurrences",
    "columns": [
      "id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "generation",
      "present",
      "source_rowid",
      "source_json",
      "legacy_store_kind",
      "legacy_provider",
      "legacy_object_key",
      "expected_purpose",
      "observed_epoch",
      "observed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_operation_adjudications",
    "columns": [
      "operation_id",
      "adjudication_id",
      "adjudication_request_sha256"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "file_shadow_operations",
    "columns": [
      "id",
      "occurrence_id",
      "captured_epoch",
      "baseline_sha256",
      "purpose",
      "access_scope",
      "source_store_kind",
      "source_provider",
      "source_object_key",
      "source_profile_id",
      "source_profile_revision",
      "source_expected_byte_size",
      "source_expected_sha256",
      "destination_profile_id",
      "destination_profile_revision",
      "status",
      "created_by",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_profile_enablements",
    "columns": [
      "storage_profile_id",
      "configuration_revision",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "file_shadow_reconciliations",
    "columns": [
      "id",
      "attempt_id",
      "runtime_incarnation",
      "verified_epoch",
      "verified_byte_size",
      "verified_sha256",
      "source_verified_at",
      "destination_verified_at",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "file_shadow_runtime_guard",
    "columns": [
      "singleton",
      "incarnation",
      "enabled",
      "enabled_by",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "file_shadow_runtime_incarnations",
    "columns": [
      "incarnation",
      "enabled_by",
      "enabled_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "incarnation"
    ]
  },
  {
    "name": "file_shadow_withdrawals",
    "columns": [
      "operation_id",
      "request_json",
      "request_sha256",
      "created_by",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "files",
    "columns": [
      "id",
      "purpose",
      "access_scope",
      "expected_byte_size",
      "expected_sha256",
      "verified_sha256",
      "state",
      "active_location_id",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "import_file_acceptances",
    "columns": [
      "import_id",
      "item_id",
      "purpose",
      "storage_profile_id",
      "storage_profile_revision",
      "role_policy_revision",
      "expected_sha256",
      "expected_byte_size",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "result_file_id",
      "result_location_id",
      "created_at",
      "completed_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "import_id",
      "item_id"
    ]
  },
  {
    "name": "imports",
    "columns": [
      "id",
      "status",
      "source_filename",
      "source_sha256",
      "sheet_name",
      "template_type",
      "recipe_family_id",
      "template_version_id",
      "workbook_asset_key",
      "manifest_asset_key",
      "warning_count",
      "error_message",
      "actor_email",
      "created_at",
      "completed_at",
      "operation_id",
      "lease_expires_at",
      "finalization_id",
      "recovery_operation_id",
      "client_request_id",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "accepted_result_json",
      "workbook_file_id",
      "manifest_file_id",
      "file_targets_protocol",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "legacy_file_mappings",
    "columns": [
      "store_kind",
      "provider",
      "object_key",
      "file_id",
      "location_id",
      "classification",
      "evidence_json",
      "observed_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "managed_storage_objects",
    "columns": [
      "id",
      "provider",
      "object_key",
      "original_name",
      "mime_type",
      "byte_size",
      "sha256",
      "status",
      "actor_email",
      "created_at",
      "orphaned_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "metrology_reference_upload_requests",
    "columns": [
      "id",
      "actor_email",
      "client_request_id",
      "operation_id",
      "template_version_id",
      "candidate_reference_id",
      "publication_plan_json",
      "ingress",
      "purpose",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "metrology_template_references",
    "columns": [
      "id",
      "template_version_id",
      "asset_id",
      "display_name",
      "position",
      "actor_email",
      "created_at",
      "deleted_at",
      "deleted_by",
      "superseded_by_occurrence_id",
      "superseded_at",
      "superseded_by",
      "supersession_operation_id",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_content_attachments",
    "columns": [
      "project_content_id",
      "asset_id",
      "storage_object_id",
      "original_name",
      "mime_type",
      "byte_size",
      "created_by",
      "created_at",
      "creation_operation_id",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "project_content_id"
    ]
  },
  {
    "name": "project_contents",
    "columns": [
      "id",
      "project_id",
      "content_type",
      "markdown_source",
      "attachment_caption",
      "attachment_source_url",
      "format_version",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_edges",
    "columns": [
      "id",
      "project_id",
      "source_item_id",
      "target_item_id",
      "source_handle",
      "target_handle",
      "marker_start",
      "marker_end",
      "label",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_items",
    "columns": [
      "id",
      "project_id",
      "item_type",
      "project_content_id",
      "reference_target_id",
      "created_sequence",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "project_map_placements",
    "columns": [
      "id",
      "project_item_id",
      "x",
      "y",
      "width",
      "height",
      "z_index",
      "revision",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "projects",
    "columns": [
      "id",
      "title",
      "revision",
      "next_created_sequence",
      "last_mutation_id",
      "created_by",
      "updated_by",
      "created_at",
      "updated_at",
      "deleted_at",
      "deleted_by",
      "deletion_operation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "r2_upload_requests",
    "columns": [
      "id",
      "actor_email",
      "client_request_id",
      "operation_id",
      "ingress",
      "purpose",
      "request_sha256",
      "request_input_json",
      "request_scope",
      "storage_profile_id",
      "storage_profile_revision",
      "storage_policy_revision",
      "candidate_asset_id",
      "candidate_object_key",
      "status",
      "accepted_result_json",
      "created_at",
      "completed_at",
      "expires_at",
      "role_policy_revision"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recipe_change_proposals",
    "columns": [
      "id",
      "recipe_family_id",
      "source_template_version_id",
      "source_verification_id",
      "change_type",
      "body",
      "status",
      "actor_email",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recipe_families",
    "columns": [
      "id",
      "name",
      "template_type",
      "created_by",
      "created_at",
      "archived_at",
      "archived_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "recovery_file_alias_evidence",
    "columns": [
      "evidence_id",
      "table_name",
      "alias_id",
      "original_json",
      "destination_file_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "evidence_id",
      "table_name",
      "alias_id"
    ]
  },
  {
    "name": "recovery_file_binding_evidence",
    "columns": [
      "evidence_id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot",
      "purpose",
      "source_file_id",
      "row_sha256",
      "preview_origin_json"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "evidence_id",
      "consumer_kind",
      "consumer_id",
      "consumer_sub_id",
      "file_slot"
    ]
  },
  {
    "name": "recovery_file_evidence",
    "columns": [
      "id",
      "backup_id",
      "source_image_sha256",
      "destination_metadata_sha256",
      "source_locator_json",
      "source_file_id",
      "destination_file_id",
      "location_id",
      "profile_id",
      "profile_revision",
      "namespace_identity",
      "object_key",
      "purpose",
      "byte_size",
      "sha256",
      "verification_operation_id",
      "verified_at",
      "published_at",
      "producer_trust",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "reference_targets",
    "columns": [
      "id",
      "registry_version",
      "target_type",
      "target_id",
      "first_registered_at",
      "last_validated_at",
      "tombstoned_at",
      "last_known_contexts_json"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_attempts",
    "columns": [
      "id",
      "job_id",
      "logical_file_id",
      "file_id",
      "location_id",
      "object_key",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "state",
      "created_at",
      "write_started_at",
      "io_settled_at",
      "verified_byte_size",
      "verified_sha256",
      "verified_at",
      "verified_owner_token",
      "verified_generation",
      "verified_runtime_incarnation",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_files",
    "columns": [
      "job_id",
      "logical_file_id",
      "entry_kind",
      "purpose",
      "byte_size",
      "sha256",
      "archive_path",
      "alias_original_name",
      "alias_created_at",
      "media_type",
      "source_file_id",
      "source_alias_id",
      "source_location_id",
      "source_profile_id",
      "source_profile_revision",
      "source_namespace",
      "source_object_key",
      "hold_operation_id",
      "target_profile_id",
      "target_profile_revision",
      "target_namespace",
      "target_policy_revision",
      "candidate_file_id",
      "candidate_asset_id",
      "archive_entry_json",
      "reuse_file_id",
      "reuse_location_id",
      "reuse_asset_id",
      "state",
      "result_file_id",
      "result_location_id",
      "updated_at",
      "reason"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "logical_file_id"
    ]
  },
  {
    "name": "research_package_identity_maps",
    "columns": [
      "job_id",
      "entity_kind",
      "source_id",
      "destination_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "entity_kind",
      "source_id"
    ]
  },
  {
    "name": "research_package_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "kind",
      "input_json",
      "package_id",
      "source_installation_id",
      "source_upload_job_id",
      "package_digest",
      "destination_scope",
      "copy_identity",
      "accepted_at",
      "target_policy_json",
      "domain_plan_json",
      "frozen_archive_json",
      "state",
      "phase",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "actor_checked_at",
      "updated_at",
      "result_json",
      "reason",
      "expires_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "research_package_records",
    "columns": [
      "job_id",
      "record_kind",
      "source_id",
      "record_json",
      "ordinal"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "job_id",
      "record_kind",
      "source_id"
    ]
  },
  {
    "name": "research_package_requests",
    "columns": [
      "actor",
      "request_id",
      "input_json",
      "job_id",
      "accepted_at",
      "reused"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "actor",
      "request_id"
    ]
  },
  {
    "name": "research_package_source_identity",
    "columns": [
      "singleton",
      "installation_id"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "run_plan_revisions",
    "columns": [
      "id",
      "run_id",
      "revision_no",
      "template_version_id",
      "effective_after_step_id",
      "reason",
      "actor_email",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_assets",
    "columns": [
      "id",
      "run_step_id",
      "asset_id",
      "role",
      "position",
      "actor_email",
      "created_at",
      "deleted_at",
      "deleted_by",
      "last_mutation_id",
      "superseded_by_occurrence_id",
      "superseded_at",
      "superseded_by",
      "supersession_operation_id",
      "filename",
      "mime_type",
      "byte_size",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_comments",
    "columns": [
      "id",
      "run_step_id",
      "scope",
      "operation_group_id",
      "asset_id",
      "actor_email",
      "created_at",
      "submission_id",
      "updated_at",
      "updated_by",
      "deleted_at",
      "deleted_by",
      "asset_deleted_at",
      "asset_deleted_by",
      "last_mutation_id",
      "deletion_operation_id",
      "asset_deletion_operation_id",
      "legacy_body",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "run_step_plan_links",
    "columns": [
      "run_plan_revision_id",
      "template_step_id",
      "run_step_id",
      "relation",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "run_plan_revision_id",
      "template_step_id",
      "run_step_id"
    ]
  },
  {
    "name": "run_steps",
    "columns": [
      "id",
      "run_id",
      "previous_step_id",
      "position",
      "origin",
      "plan_status",
      "template_step_id",
      "logical_step_key",
      "definition_hash",
      "expected_state_hash",
      "title",
      "status",
      "notes",
      "tool_name",
      "parameters_text",
      "comments_text",
      "deviation_note",
      "actualized_at",
      "created_at",
      "updated_by",
      "last_mutation_id",
      "updated_at",
      "entry_kind",
      "deleted_at",
      "deleted_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "runs",
    "columns": [
      "id",
      "sample_id",
      "recipe_family_id",
      "template_version_id",
      "current_plan_revision_id",
      "predecessor_run_id",
      "anchor_step_id",
      "sequence_no",
      "run_group_id",
      "template_name_snapshot",
      "template_type_snapshot",
      "template_version_snapshot",
      "status",
      "created_by",
      "created_at",
      "completed_at",
      "initial_state_hash",
      "run_kind",
      "deleted_at",
      "deleted_by",
      "last_mutation_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "samples",
    "columns": [
      "id",
      "code",
      "title",
      "description",
      "status",
      "location",
      "parent_id",
      "pinned",
      "created_by",
      "updated_by",
      "last_mutation_id",
      "created_at",
      "updated_at",
      "inherited_state_hash",
      "deleted_at",
      "deleted_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "state_representation_assets",
    "columns": [
      "state_hash",
      "asset_id",
      "position",
      "file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "state_hash",
      "asset_id"
    ]
  },
  {
    "name": "state_representations",
    "columns": [
      "hash",
      "hash_scheme",
      "representation_type",
      "logical_state_key",
      "content_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "hash"
    ]
  },
  {
    "name": "state_verification_steps",
    "columns": [
      "verification_id",
      "run_step_id",
      "ordinal"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "verification_id",
      "run_step_id"
    ]
  },
  {
    "name": "state_verifications",
    "columns": [
      "id",
      "sample_id",
      "after_run_step_id",
      "previous_verification_id",
      "run_plan_revision_id",
      "expected_state_hash",
      "result",
      "evidence_asset_id",
      "note",
      "status",
      "actor_email",
      "created_at",
      "evidence_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "step_definitions",
    "columns": [
      "hash",
      "hash_scheme",
      "name",
      "tool_name",
      "parameters_text",
      "comments_text",
      "canonical_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "hash"
    ]
  },
  {
    "name": "storage_profile_activations",
    "columns": [
      "operation_id",
      "storage_profile_id",
      "configuration_revision",
      "action",
      "candidate_profile_id",
      "candidate_revision",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "binding_revision",
      "actor",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "storage_profile_admissions",
    "columns": [
      "operation_id",
      "native_profile_id",
      "candidate_profile_id",
      "candidate_revision",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "actor",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "storage_profile_runtime",
    "columns": [
      "storage_profile_id",
      "state",
      "registered_at",
      "activated_at",
      "retired_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "storage_profiles",
    "columns": [
      "id",
      "adapter_type",
      "namespace_identity",
      "configuration_source",
      "credential_reference",
      "configuration_revision",
      "state",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "storage_role_defaults",
    "columns": [
      "role",
      "storage_profile_id",
      "storage_profile_revision",
      "policy_revision",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "role"
    ]
  },
  {
    "name": "storage_role_policy_revisions",
    "columns": [
      "policy_revision",
      "role",
      "storage_profile_id",
      "storage_profile_revision",
      "operation_id",
      "actor",
      "created_at"
    ],
    "withoutRowid": true,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "policy_revision",
      "role"
    ]
  },
  {
    "name": "system_recovery_attempts",
    "columns": [
      "id",
      "job_id",
      "generation",
      "runtime_incarnation",
      "owner_token",
      "object_key",
      "expected_byte_size",
      "expected_sha256",
      "state",
      "created_at",
      "settled_at",
      "verified_at",
      "cleaned_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_recovery_files",
    "columns": [
      "job_id",
      "id",
      "ordinal",
      "outcome",
      "file_json"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "id"
    ]
  },
  {
    "name": "system_recovery_jobs",
    "columns": [
      "id",
      "request_id",
      "actor",
      "kind",
      "state",
      "phase",
      "input_json",
      "accepted_at",
      "updated_at",
      "reason",
      "generation",
      "owner_token",
      "runtime_incarnation",
      "lease_expires_at",
      "source_upload_job_id",
      "target_id",
      "target_incarnation",
      "checkpoint_json",
      "source_checkpoint",
      "artifact_key",
      "archive_byte_size",
      "archive_sha256",
      "expires_at",
      "completed_files",
      "total_files",
      "bytes_done",
      "bytes_total",
      "result_json"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_recovery_legacy_holds",
    "columns": [
      "job_id",
      "store_kind",
      "provider",
      "object_key",
      "released_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "store_kind",
      "provider",
      "object_key"
    ]
  },
  {
    "name": "system_recovery_maintenance",
    "columns": [
      "singleton",
      "state",
      "generation",
      "token",
      "requested_by",
      "backup_job_id",
      "checkpoint_sha256",
      "started_at",
      "fenced_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_maintenance_requests",
    "columns": [
      "request_id",
      "actor",
      "action",
      "expected_generation",
      "result_json",
      "created_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "request_id"
    ]
  },
  {
    "name": "system_recovery_metadata_chunks",
    "columns": [
      "job_id",
      "name",
      "ordinal",
      "chunk"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "name",
      "ordinal"
    ]
  },
  {
    "name": "system_recovery_requests",
    "columns": [
      "request_id",
      "actor",
      "job_id",
      "input_sha256",
      "accepted_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "actor",
      "request_id"
    ]
  },
  {
    "name": "system_recovery_runtime",
    "columns": [
      "singleton",
      "enabled",
      "incarnation",
      "installation_id",
      "last_heartbeat_at",
      "updated_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_target_claim",
    "columns": [
      "singleton",
      "target_id",
      "job_id",
      "incarnation",
      "challenge",
      "schema_sha256",
      "image_sha256",
      "status",
      "cursor_json",
      "verified_at",
      "owner_token",
      "generation",
      "runtime_incarnation",
      "lease_expires_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "singleton"
    ]
  },
  {
    "name": "system_recovery_target_files",
    "columns": [
      "job_id",
      "logical_id",
      "source_blob_id",
      "file_id",
      "location_id",
      "profile_id",
      "namespace",
      "object_key",
      "purpose",
      "byte_size",
      "sha256",
      "state",
      "owner_token",
      "generation",
      "incarnation",
      "verified_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "logical_id"
    ]
  },
  {
    "name": "system_recovery_target_provenance",
    "columns": [
      "job_id",
      "ordinal",
      "image_sha256",
      "chunk",
      "created_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id",
      "ordinal"
    ]
  },
  {
    "name": "system_recovery_write_leases",
    "columns": [
      "id",
      "owner",
      "kind",
      "generation",
      "created_at",
      "expires_at",
      "released_at"
    ],
    "withoutRowid": false,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_research_package_cleanup_grants",
    "columns": [
      "job_id",
      "runtime_incarnation",
      "requested_at",
      "actor",
      "mode"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "job_id"
    ]
  },
  {
    "name": "system_storage_candidate_check_audit",
    "columns": [
      "id",
      "check_id",
      "operation",
      "execution_token",
      "actor",
      "status",
      "write_outcome",
      "read_outcome",
      "metadata_outcome",
      "delete_outcome",
      "cleanup_outcome",
      "result_code",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_candidate_checks",
    "columns": [
      "id",
      "profile_id",
      "configuration_revision",
      "credential_ref",
      "envelope_revision",
      "namespace_json",
      "namespace_sha256",
      "configuration_sha256",
      "envelope_version",
      "key_id",
      "nonce",
      "ciphertext",
      "probe_key",
      "payload_sha256",
      "payload_size",
      "requested_by",
      "created_at",
      "execution_kind",
      "execution_token",
      "execution_deadline",
      "execution_actor",
      "status",
      "write_outcome",
      "read_outcome",
      "metadata_outcome",
      "delete_outcome",
      "cleanup_outcome",
      "result_code",
      "updated_at",
      "completed_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_configuration_audit",
    "columns": [
      "id",
      "profile_id",
      "configuration_revision",
      "actor",
      "operation",
      "outcome",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "system_storage_configuration_revisions",
    "columns": [
      "profile_id",
      "revision",
      "label",
      "namespace_json",
      "credential_ref",
      "created_at",
      "created_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "profile_id",
      "revision"
    ]
  },
  {
    "name": "system_storage_credential_descriptors",
    "columns": [
      "credential_ref",
      "profile_id",
      "configuration_revision",
      "namespace_sha256",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "credential_ref"
    ]
  },
  {
    "name": "system_storage_credential_payloads",
    "columns": [
      "credential_ref",
      "envelope_revision",
      "envelope_version",
      "key_id",
      "nonce",
      "ciphertext"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "credential_ref"
    ]
  },
  {
    "name": "system_storage_credential_reenvelopes",
    "columns": [
      "operation_id",
      "profile_id",
      "configuration_revision",
      "credential_ref",
      "previous_envelope_revision",
      "envelope_revision",
      "outcome",
      "previous_key_id",
      "key_id",
      "created_at",
      "created_by"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "operation_id"
    ]
  },
  {
    "name": "system_storage_native_bindings",
    "columns": [
      "storage_profile_id",
      "candidate_profile_id",
      "candidate_revision",
      "credential_ref",
      "envelope_revision",
      "check_id",
      "configuration_sha256",
      "namespace_sha256",
      "activation_operation_id",
      "binding_revision",
      "created_at",
      "updated_at"
    ],
    "withoutRowid": true,
    "local": true,
    "classification": "local",
    "primaryKeyColumns": [
      "storage_profile_id"
    ]
  },
  {
    "name": "system_storage_profiles",
    "columns": [
      "id",
      "adapter_type",
      "namespace_json",
      "namespace_sha256",
      "latest_revision",
      "created_at"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "protected_configuration",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "template_steps",
    "columns": [
      "id",
      "template_version_id",
      "logical_step_key",
      "position",
      "source_row",
      "step_number",
      "section_name",
      "definition_hash",
      "expected_state_hash",
      "raw_json"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  },
  {
    "name": "template_versions",
    "columns": [
      "id",
      "recipe_family_id",
      "name",
      "template_type",
      "version",
      "manifest_hash",
      "initial_state_hash",
      "source_filename",
      "source_asset_key",
      "content_json",
      "created_by",
      "created_at",
      "locked_at",
      "locked_by",
      "archived_at",
      "archived_by",
      "template_kind",
      "metrology_notes",
      "deleted_at",
      "deleted_by",
      "source_file_id"
    ],
    "withoutRowid": false,
    "local": false,
    "classification": "content",
    "primaryKeyColumns": [
      "id"
    ]
  }
];
export const RECOVERY_MIGRATIONS = [
  {
    "name": "0001_v3_baseline.sql",
    "sha256": "da244690cc17e88c99628461e4c4d5b52db37334b7fd6dd04643dfa7ebe4b4d2",
    "appliedToFreshSchema": true
  },
  {
    "name": "0002_fp1_file_registry.sql",
    "sha256": "28f95dbc7fca4a824c38575ec6be998aacf0d50f25c7325ea745a5a2362d5584",
    "appliedToFreshSchema": true
  },
  {
    "name": "0003_fp1_import_acceptance.sql",
    "sha256": "c56596cb35bbadda16e8be14f8b3527a1b7384947be1a68c7604602a3d42c701",
    "appliedToFreshSchema": true
  },
  {
    "name": "0004_r2_upload_acceptance.sql",
    "sha256": "911adba4ba3c5fa6f9e560d72f337da8669cc17be4d51e470940bb86fb62c1b8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0005_metrology_reference_acceptance.sql",
    "sha256": "ddda77389c39d71d9475c0f83b04995616a8940f00be83eee27b1e9efd4bcd5e",
    "appliedToFreshSchema": true
  },
  {
    "name": "0006_comment_acceptance.sql",
    "sha256": "5f5a6354f1c55b95644fcd010631a949ba7fdb55f8c77ded7a1829be2b745de8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0007_fp1_file_authority_transition.sql",
    "sha256": "252123f4e901f2c6ae970f84c25fe34d9ef3f3433fcc144ca583c70b4556218d",
    "appliedToFreshSchema": true
  },
  {
    "name": "0008_fp1_shadow_runtime.sql",
    "sha256": "324ab0ec3ce282f13b7ee0caae1be1977d817bbd448836925090b72709bd2dfc",
    "appliedToFreshSchema": true
  },
  {
    "name": "0009_fp1_shadow_withdrawals.sql",
    "sha256": "8394abf5853cb3217da8c5d5b2b1b29188f1f0100d90b8fdc9b569c8621283f8",
    "appliedToFreshSchema": true
  },
  {
    "name": "0010_fp1_shadow_adjudications.sql",
    "sha256": "6038d51909b8d2fa8ad1d1d3eba4bd96808bb7d4b9a42fafeaeb10b36d40a1a0",
    "appliedToFreshSchema": true
  },
  {
    "name": "0011_fp1_retire_legacy_test_projects.sql",
    "sha256": "177d3e751bb066dec3b1fcfe78f90703f24f8817b45ce8a6ee861b6d86b6011a",
    "appliedToFreshSchema": false
  },
  {
    "name": "0012_fp1_file_authority_runtime.sql",
    "sha256": "8360b65ae1f9b199f90e88443bde82e49bb6db6cc9f9110c8bc4410b51a92fab",
    "appliedToFreshSchema": true
  },
  {
    "name": "0013_fp1_r2_role_defaults.sql",
    "sha256": "d5df0455221af4b52b007a7462b48355fdc5fc6471766979696c2545b19a2343",
    "appliedToFreshSchema": true
  },
  {
    "name": "0014_fp2_storage_configuration.sql",
    "sha256": "427f022d84086aa29ac34a3b0540e70807fc68e3815e2db98312614028e00d54",
    "appliedToFreshSchema": true
  },
  {
    "name": "0015_fp2_storage_candidate_checks.sql",
    "sha256": "f2558f69ea77c6382e44f705e76fcc2ed56ad320274c43a3ad0be0afa8cc40c3",
    "appliedToFreshSchema": true
  },
  {
    "name": "0016_fp2_credential_reenvelopes.sql",
    "sha256": "6b622eaa0fccca4b241a803bcb3b0ee19688d432648d28eb80f34b0afffc36c3",
    "appliedToFreshSchema": true
  },
  {
    "name": "0017_fp2_native_storage_profiles.sql",
    "sha256": "94919cde4b666e6243358ee328bdc53f7572dbbb5f42ae9a4a4f94dc5a7e4057",
    "appliedToFreshSchema": true
  },
  {
    "name": "0018_fp2_native_file_runtime.sql",
    "sha256": "76a72e55cd0cadaf48ccedf559cdd411ba26e93096578cdd99fce9c89ab0fe6d",
    "appliedToFreshSchema": true
  },
  {
    "name": "0019_fp3_file_jobs.sql",
    "sha256": "23d216a71383b4238a9dbf73e98e0252173ba94c1af13b2892e0eb798e4d19a4",
    "appliedToFreshSchema": true
  },
  {
    "name": "0020_fp4_research_packages.sql",
    "sha256": "0dc7a2248a06a434cf92ca7f647bab4c50ad7f6419c792d10ec13b05b94c44b4",
    "appliedToFreshSchema": true
  },
  {
    "name": "0021_fp5_system_recovery.sql",
    "sha256": "834df694d90705962b6a8d81e97b0c1cf9b4514ff270f954e29d2080b596a3e1",
    "appliedToFreshSchema": true
  },
  {
    "name": "0022_fp5_recovery_evidence.sql",
    "sha256": "b637e7e901168e11276b76040cd0a1c45693884a35ad35b5279527e54609ee48",
    "appliedToFreshSchema": true
  }
] as const;
